Plugin YAML Update
EssentialsX/Essentials pull request #1369
Opened 2017-07-06 23:59 UTC by pablo67340

Update plugin YAML containing all Essentials Permission nodes,
descriptions and defaults. This is required by other programs/plugins.

2017-07-07 00:06 UTC, pablo67340 commented
Ignore the first commit. I had accidentally pasted all the perms without indentation, thus resulting in a syntax error. I've gone and re-pasted them with the correct indentation required for YAML.

2017-07-09 14:20 UTC, mdcfe requested changes
I've looked through and left comments on anything I noticed that doesn't look right. Was there a reason for omitting the dashes? They appear to be present on the Essentials wiki page.

2017-07-09 14:20 UTC, md678685 commented on Essentials/src/plugin.yml
> +    description: If permission based item spawn: Spawn <itemname.
This should have a closing >.

2017-07-09 14:20 UTC, md678685 commented on Essentials/src/plugin.yml
> +    description: If permission based item spawn: Spawn [itemid.
Same as above, but with a ].

2017-07-09 14:20 UTC, md678685 commented on Essentials/src/plugin.yml
> +  essentials.itemspawn.meta chapter [chapter]:
As far as I can tell, this should have dashes (unless YAML breaks if they are added).

2017-07-09 14:20 UTC, md678685 commented on Essentials/src/plugin.yml
> +  essentials.itemspawn.item [itemid]:
Another potentially missing dash and missing closing brackets here.

2017-07-09 14:20 UTC, md678685 commented on Essentials/src/plugin.yml
> +    default: false
More potentially-missing dashes.

2017-07-09 14:20 UTC, md678685 commented on Essentials/src/plugin.yml
> +    default: false
The `essentials.spawner.[mob]` and `essentials.spawner.*` perms are presumably only for `/spawner` and not `/spawnmob`.

2017-07-09 14:20 UTC, md678685 commented on Essentials/src/plugin.yml
> +    description: Allows   essentials.commands to be used while jailed (requires regular perm).
Extra spaces here.

2017-07-11 19:39 UTC, pablo67340 commented
The reason being was I used a few small tricks to actually copy/paste directly from the Wiki. My auto formatter has accidentally taken things out which I've missed. This took me about 30 min to throw together, saved a ton of time. I will fix right now.

2017-07-12 07:20 UTC, md678685 commented
I guessed that they were taken from the wiki :p

I'll check over the PR again in a bit.

2017-07-12 07:23 UTC, mdcfe reviewed
Are the added permissions from the EssentialsX changes wiki included here? If so, this looks good.

2017-08-03 23:32 UTC, SupaHam commented
I don't think we should be adding permissions that contain parameters. Bukkit will register them as permissions when in fact they are not the real permissions used.

2017-09-06 15:48 UTC, pablo67340 commented
So shall I remove them entirely?

2017-09-06 16:34 UTC, md678685 commented
I think it would be best to keep the base permissions of the perms with parameters and remove the ones that actually have the parameters.

2017-09-06 20:47 UTC, pablo67340 commented
There we go, let me know what you think.

2017-11-23 19:52 UTC, mdcfe submitted a review, later dismissed

2018-01-22 02:08 UTC, drtshock commented
Late to the party but why default to false? That will mean that ops don't have permission to do anything.

2018-12-31 10:08 UTC, DoNotSpamPls requested changes
The permissions should be default: op
Also, dashes are still missing and I'm not even sure that YAML allows the -[] syntax you've used

2020-03-31 02:35 UTC, Ichbinjoe commented
This is likely out of date and dead. Reopen if not.

2020-03-31 02:35 UTC, closed without merging