Don't add duplicate usernames to vanished player list
EssentialsX/Essentials pull request #1789
Opened 2018-01-22 13:09 UTC by md678685

This should fix the long standing bug with vanish not working properly, by not adding players to the vanished player list more than once.

However, an **alternative** approach was outlined in #1764 ([here](https://github.com/EssentialsX/Essentials/issues/1764#issuecomment-357887279)):
> ...we could replace the list with a `Set` and deprecate the existing `getVanishedPlayers`, especially considering since there's no reason for plugins to directly mutate the `ess.vanishedPlayers` list instead of using the appropriate `User` method.

@drtshock @SupaHam Thoughts on this PR's approach versus the alternative approach described above?

2018-01-22 18:11 UTC, drtshock commented
I would be in favor of changing it to a set and just deprecating the method for a few versions to allow compatibility.

2018-01-23 11:15 UTC, SupaHam requested changes
Yes, change `vanishedPlayers` to `Set`, probably `LinkedSet`, as that is exactly the behaviour this PR implements inconsistently.

2018-01-23 12:51 UTC, md678685 commented
Okay, will do when I get a chance.

2018-02-14 21:35 UTC, md678685 commented
Closing in favour of #1796.

2018-02-14 21:35 UTC, closed without merging