Fixes #1794
EssentialsX/Essentials pull request #1811
Opened 2018-01-26 21:30 UTC by AgentTroll

Fixes #1794

An empty MOTD file would cause the user to be displayed the unknown page error message upon joining.

This PR proposes a fix that will check to make sure there are pages in the first place before displaying an error message.

One concern I still have is that the `/motd` command will not output anything after this change, which I suppose could possibly be desirable, but at the same time, I feel like there should be some response to at least the command even if the user does not receive a message on join.

2018-01-26 21:59 UTC, md678685 commented
I disagree with the purpose of this PR: if people manually try to view invalid pages, they should be informed that those pages are invalid, rather than just receive no output whatsoever, even if the file it's reading from was empty in the first place.

To fix the MOTD issue alone (#1794), I would simply check whether an MOTD exists before scheduling the MOTD-on-login task. This way, command behaviour doesn't change, meaning that if users run a command that should read text from a file, at least they should receive a message to inform them as to why it didn't work.

2018-01-26 21:59 UTC, mdcfe reviewed
See above comment.

2018-01-26 22:00 UTC, mdcfe requested changes
See above comment. ~~github why do you bork~~

2018-01-26 22:13 UTC, AgentTroll commented
Done.

2018-01-26 22:23 UTC, mdcfe approved these changes

2018-01-31 09:10 UTC, LaxWasHere approved these changes

2018-01-31 23:11 UTC, drtshock approved these changes

2018-02-01 01:01 UTC, merged