Update to java 8
EssentialsX/Essentials pull request #1818
Opened 2018-01-28 18:44 UTC by NJDaeger

This needs to be done at some point. Was hoping it could be now. Considering that Java 7 is EOL and Mojang themselves don't support Java 7 anymore, I think this is a change that should be merged.

2018-01-28 21:26 UTC, mdcfe approved these changes

2018-01-29 17:18 UTC, DoNotSpamPls approved these changes
There is no need to support Java 1.7 anymore imo. There are more people using Java 9 than Java 7, which should tell you what we need to support.

![](https://bitcoin.is-serious.business/a0b322.png)

2018-01-29 18:30 UTC, caojohnny approved these changes

2018-01-29 18:54 UTC, md678685 commented
Shouldn't all the separate modules also be updated at the same time?

2018-01-29 19:50 UTC, kashike approved these changes

2018-01-29 22:56 UTC, drtshock requested changes
I disagree with this PR. I don't think we should be updating to a java version that will break support for even a fraction of our user base. Operating at the scale we do, 0.5% of users is still at least 100 servers (and that only counts users that opt in to reporting stats).

The only way (currently) that I could see us updating is if we decided *not* to provide any backward compatibility with the 1.13 update.

2018-01-30 12:35 UTC, SupaHam commented
I am for java 8 starting on 1.13. There's no need to force this upgrade right now. We are way beyond EOL, so it is only right we aim for java 8 sooner rather than later.

2018-01-30 12:36 UTC, SupaHam requested changes
Await 1.13

2018-01-30 19:46 UTC, closed without merging