Update messages_nl.properties
EssentialsX/Essentials pull request #1888
Opened 2018-03-10 18:55 UTC by DutchUser

Changed English lines to Dutch.

2018-03-10 18:58 UTC, DutchUser commented
I also took a few other with me, (I changed more then i said on https://github.com/EssentialsX/Essentials/issues/1887 

Its because i saw those too when i was scrolling and editing the english one's.

PS: Its the first time ever i used the PR on any plugin. So sorry if i screwed something up or make an mistake with making the PR.

2018-03-11 07:33 UTC, mdcfe requested changes
Just a couple of minor things that need to be taken care of, but otherwise this looks good.

2018-03-11 07:33 UTC, md678685 commented on Essentials/src/messages_nl.properties
> +typeTpacancel=\u00a76om dit te annuleren, typ \u00a7c/tpacancel\u00a76.
This like should start with a capital letter.

2018-03-11 07:33 UTC, md678685 commented on Essentials/src/messages_nl.properties
> +clearInventoryConfirmToggleOn=\u00a76\u00a76Je zal nu worden gevraagd om de inventory clear te bevestigen.
There is a duplicate `\u00a76` on this line.

2018-03-25 21:02 UTC, mdcfe approved these changes

2018-03-25 21:02 UTC, merged