Replaced msgFormat with msgFormatIn and msgFormatOut for better customization.
EssentialsX/Essentials pull request #2013
Opened 2018-05-21 22:37 UTC by StiegeRobin

Replaced msgFormat with msgFormatIn and msgFormatOut for better customization.
Modified messages.properties.

2018-05-21 23:40 UTC, drtshock approved these changes

2018-05-23 04:58 UTC, mdcfe requested changes

2018-05-23 04:58 UTC, md678685 commented on Essentials/src/messages.properties
> -msgFormat=\u00a76[\u00a7c{0}\u00a76 -> \u00a7c{1}\u00a76] \u00a7r{2}
This will suddenly break people's message formatting without warning - is this what we want?

2018-05-23 04:58 UTC, md678685 commented on Essentials/src/messages_da.properties
> +msgFormatOut=\u00a76[\u00a7c{0}\u00a76 -> \u00a7c{1}\u00a76] \u00a7r{2}msgIgnore=\u00a7c{0} \u00a74has messages disabled.
There needs to be a newline between the two messages here.

2019-12-28 15:07 UTC, Ichbinjoe commented
This issue hasn't had any activity in quite awhile. Closing.

2019-12-28 15:07 UTC, closed without merging