[Feature] Per Request - Send message to player on teleporting home
EssentialsX/Essentials pull request #2179
Opened 2018-09-12 14:23 UTC by darbyjack

Fixes #2162

2018-09-13 06:20 UTC, Xeyame approved these changes

2019-04-17 06:35 UTC, Ichbinjoe approved these changes
This PR is ready to go minus needing l18s updated

2019-04-17 11:03 UTC, mdcfe requested changes

2019-04-17 11:03 UTC, md678685 commented on Essentials/src/messages_cs.properties
> +teleportHome=\u00a76Teleporting to {0}.
Due to th Crowdin integration, these need removing from each translated messages file - added messages should now be in `messages.properties`, and Crowdin will handle the rest.

2019-04-17 18:33 UTC, Ichbinjoe commented
Closing since it requires a bunch of changes and the original branch no longer exists.

2019-04-17 18:33 UTC, closed without merging