Hiding display names
EssentialsX/Essentials pull request #2248
Opened 2018-11-02 18:14 UTC by AllTheMegahertz

Prevents a user's nickname from appearing if they are hidden. Closes issue #2221

2018-11-04 15:32 UTC, mdcfe requested changes
I would be fine with this approach, as long as we're willing to accept that display names will not be visible anywhere while players are hidden.

However, this may have unforeseen side effects, so I'd prefer this to be behind a config toggle like `hide-displayname-in-vanish` defaulting to true.

2018-11-05 13:34 UTC, AllTheMegahertz commented
Good idea, just added that now. I've tested it and it seems to work perfectly.

2018-11-11 12:52 UTC, mdcfe approved these changes

2018-11-11 12:54 UTC, mdcfe requested changes

2018-11-11 12:54 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/Settings.java
> +        return config.getBoolean("hide-displayname-in-vanish", true);
This should have a default of false, as old configs will not have this option.

2018-11-12 08:10 UTC, mdcfe approved these changes

2018-11-12 08:31 UTC, md678685 commented
Thanks for making these changes - I'll merge this PR when I get a chance.

2018-12-09 11:02 UTC, merged