Addresses issue #2512
EssentialsX/Essentials pull request #2518
Opened 2019-05-03 13:48 UTC by willjallen

Added permission 'essentials.jump.pastWorldBorder'
Added check if player has permission to /jump past the world border

2019-05-03 19:50 UTC, Xeyame commented
Shouldn't all permissions be fully lowercase, and should we make the "You can not jump outside of the world border" message configurable?, Everything else looks good to me.

2019-05-03 20:18 UTC, pop4959 requested changes

2019-05-03 20:18 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandjump.java
> +        if(Bukkit.getWorld(user.getWorld().getUID()).getWorldBorder().isInside(loc) || user.isAuthorized("essentials.jump.pastWorldBorder")) {
You should add a space between the "if" and "(" to follow the convention of the other code in this file. Also, likewise, conventionally permissions are lower case and short / to the point. Something like "essentials.jump.border" might be better.

2019-05-03 20:18 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandjump.java
> +        }else {
space

2019-05-03 20:18 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandjump.java
> +            user.sendMessage("You can not jump outside of the world border");
Messages in Essentials should be configurable. You can look at some other code or pull requests in Essentials to get an idea of how you should accomplish this. It is not too hard, and many servers will want to change the message to something else.

2019-05-06 20:33 UTC, drtshock commented
You need to add the tl keys to all the translation files. Just leave the message in English though.

2019-05-07 08:45 UTC, md678685 commented
@drtshock Crowdin will add them to each file once the PR is merged and the translation is approved.

2019-05-07 19:05 UTC, drtshock commented
ooo

2019-12-28 15:28 UTC, Ichbinjoe approved these changes
Conditional approval once comments are removed.

2019-12-28 15:28 UTC, Ichbinjoe commented on Essentials/src/com/earth2me/essentials/Teleport.java
> +        if (!loc.getWorld().getWorldBorder().isInside(loc)
Locations are always assumed to have a valid world afaik. If they didn't we would have some other problems.

2019-12-28 15:28 UTC, Ichbinjoe commented on Essentials/src/com/earth2me/essentials/Teleport.java
> +            if (teleportOwner != teleportee) { // I think this will check if you are using #teleportOther()?
Yes! Comment needs removed.

2020-05-11 16:34 UTC, mdcfe requested changes
A couple of concerns:
* This PR will need to be updated to include AsyncTeleport once it has been merged - see #3102.
* What behaviour exactly will this change? Does this break warps or jails?

2020-05-11 16:34 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/Teleport.java
> +        if (!loc.getWorld().getWorldBorder().isInside(loc)
```suggestion
        if (!loc.getWorld().getWorldBorder().isInside(loc)
```

2020-05-11 16:34 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/Teleport.java
> +            if (teleportOwner != teleportee) { // I think this will check if you are using #teleportOther()?
```suggestion
            if (teleportOwner != teleportee) {
```

2020-07-24 08:12 UTC, pop4959 commented
Closing due to author inactivity. Can re-open if there are signs of life, especially addressing any concerns that have been mentioned.

2020-07-24 08:12 UTC, closed without merging