More 1.14 Progress
EssentialsX/Essentials pull request #2523
Opened 2019-05-06 23:41 UTC by JRoy

This pull request adds much of the mob and item work for you minus backward compatibility.

# Changelog:
* Targets 1.14-R0.1
* Adds 1.14 Mobs
* Adds 1.14 Items
  * Updated Signs as Well
* Fixes Misc Build Errors

# Notes While Testing:
* Signs work as intended
* Sometimes while moving after being AFK there is an error due to Spigot's new enforcement of async/sync events:
  * ```java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
        at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
        at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener.delayedJoin(EssentialsPlayerListener.java:221) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener$1.run(EssentialsPlayerListener.java:198) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.jar:git-Spigot-1eece4f-fe1199c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]```

Hope this helps :)

2019-05-07 07:03 UTC, mdcfe requested changes
Thank for the PR, but the majority of the changes will need refactoring at some point:
* We're currently still aiming to support 1.12.2 (and 1.8 as long as feasible)
* We have an automated tool to update `items.json`
* We're not deliberately trying to break prereleases

2019-05-07 07:03 UTC, mdcfe commented on Essentials/src/com/earth2me/essentials/MobData.java
> -    SIAMESE_CAT("siamese", EntityType.OCELOT, Ocelot.Type.SIAMESE_CAT, true),
This was left untouched as it breaks support for 1.13/1.12. I'll accept this for now but a better solution will be needed at some point.

2019-05-07 07:03 UTC, mdcfe commented on Essentials/src/com/earth2me/essentials/utils/VersionUtil.java
> +                Double.parseDouble(revision));
This will error on future prereleases; the ability to test on prereleases was the whole point of changing this.

2019-05-07 07:03 UTC, mdcfe commented on Essentials/src/items.json
> +    "oak_sign": {
This file is automatically generated, so once the tool is updated these will be redundant.

2019-05-07 23:36 UTC, JRoy commented on Essentials/src/items.json
> +    "oak_sign": {
Wish I knew that earlier :P

How do you generate that file anyway?

2019-05-08 01:27 UTC, JRoy commented
@md678685 I fixed pre-releases so now they actually work, and as for 1.12/1.13 support: I added back ocelots as the enum is just deprecated. But that obviously won't be good in the long run. I don't know how you want to maintain support so please do elaborate.

2019-05-08 12:33 UTC, mdcfe commented on Essentials/src/com/earth2me/essentials/MobData.java
> +    BABY_FOX("baby", EntityType.FOX, Data.BABY, false),
Baby foxes should already be covered by `BABY_AGEABLE`.

2019-05-08 19:04 UTC, JRoy commented
@md678685 Changes Applied 😄

2019-05-08 23:06 UTC, closed without merging