Add tab-completer for /spawnmob command
EssentialsX/Essentials pull request #2661
Opened 2019-07-09 11:32 UTC by montlikadani

2019-07-09 11:49 UTC, montlikadani commented
https://travis-ci.com/EssentialsX/Essentials/builds/118431722#L1916
wut?

2019-07-18 19:23 UTC, Omio reviewed
Beyond a mildly minimal memory impact, is this really going to change a bunch, bar for compile time?

2019-07-18 19:30 UTC, montlikadani commented
> Beyond a mildly minimal memory impact, is this really going to change a bunch, bar for compile time?

Because of many tests, there is so much to commit because Travis didn't accept it.

2019-12-29 01:07 UTC, Ichbinjoe submitted a review, later dismissed

2019-12-29 06:02 UTC, pop4959 requested changes

2019-12-29 06:02 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandspawnmob.java
> +            return java.util.Collections.emptyList();
To be consistent with the rest of the Essentials codebase, I suggest reverting this back to not using a fully qualified package name.

2019-12-29 08:43 UTC, pop4959 approved these changes

2019-12-29 15:20 UTC, Ichbinjoe approved these changes

2020-03-13 09:30 UTC, merged