.x: CUSTOM CONSOLE NAME
EssentialsX/Essentials pull request #2758
Opened 2019-08-21 21:10 UTC by darbyjack

2019-08-22 05:23 UTC, montlikadani commented on Essentials/src/com/earth2me/essentials/Console.java
> -    public static final String NAME = "Console";
space was remain

2019-10-02 21:03 UTC, pop4959 commented
Wouldn't this make more sense to implement as a locale option? This allows for translating "Console" to other languages by default as well. For example en="Console", de="Konsole". It would also clutter the settings file less.

2019-10-14 19:22 UTC, caojohnny requested changes

2019-10-14 19:22 UTC, AgentTroll commented on Essentials/src/com/earth2me/essentials/Console.java
> +    public static  String NAME = "Console";
Get rid of this. The display name should be obtained from the `ess` instance when it is called from `getDisplayName()` for example.

Another thing to consider is that this probably should be localized.

2020-04-02 20:08 UTC, closed without merging