Convert all projects to Gradle
EssentialsX/Essentials pull request #2917
Opened 2020-01-01 04:17 UTC by Ichbinjoe

Gradle > Maven, especially for lots of modules (which I plan to do).

2020-01-01 04:18 UTC, Ichbinjoe commented
Oh yeah this totally breaks the build bot.

2020-01-01 05:18 UTC, Ichbinjoe commented
Some notes:

Essentials/build/resources/main/plugin.yml has the correct version assigned to it, meaning the generated Essentials.jar will also have the same version.

Manually verified that the size of Essentials.jar is similar & has paperlib shaded to the correct place.

2020-01-01 09:00 UTC, mdcfe requested changes

2020-01-01 09:00 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsBlockListener.java
> +                    if (ess.getUser(event.getPlayer()).isAuthorized("essentials.spawnerconvert." + mobName)) {
Why are these changes in this PR?

2020-01-01 09:00 UTC, mdcfe commented on crowdin.yml
> +    translation: "/Essentials/src/main/resources/messages_%locale_with_underscore%.properties"
To do: ensure this doesn't break Crowdin or delete translations

2020-01-01 09:00 UTC, mdcfe commented on build.gradle
> +                endToken: '}', tokens: ["full.version": "${version}-${GIT_COMMIT}".toString()])
This changes the version number format which makes it useless to dev build users, who won't be able to tell what version they have from `/ess version` or the jar file name.

2020-01-01 16:26 UTC, Ichbinjoe commented on build.gradle
> +                endToken: '}', tokens: ["full.version": "${version}-${GIT_COMMIT}".toString()])
What is the actual format? Was it builds since release or something?

2020-01-01 16:26 UTC, Ichbinjoe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsBlockListener.java
> +                    if (ess.getUser(event.getPlayer()).isAuthorized("essentials.spawnerconvert." + mobName)) {
Because I made a mistake!

2020-01-02 19:22 UTC, md678685 commented on build.gradle
> +                endToken: '}', tokens: ["full.version": "${version}-${GIT_COMMIT}".toString()])
`2.x.y.z` where `2.x.y` is the last released version and `z` is the number of commits since the last tag.

2020-01-04 22:08 UTC, Ichbinjoe commented
Build passes locally - I suspect that this is instead a problem with caching an old compilation.

2020-07-26 19:48 UTC, closed without merging