Explain how to add commands to kits
EssentialsX/Essentials pull request #2980
Opened 2020-01-30 01:02 UTC by JasonHorkles

First time I've created a pull request so hopefully I did everything right

2020-01-30 13:28 UTC, mdcfe approved these changes

2020-02-05 07:29 UTC, pop4959 submitted a review, later dismissed
This is a nitpick but maybe change /ebc to /broadcast or /ebroadcast to be more clear as to what the example is executing.

And perhaps instead (or in addition to) include /give in the example since that seems to be the most common use case among server owners for commands in kits.

This isn't blocking this PR though, as it is quite minor.

2020-02-05 10:46 UTC, md678685 commented
> include /give in the example

I'm not sure this is the best idea, since it may confuse users as to what the "recommended" way to add items is. ItemMeta isn't perfect but we don't want to push people away from it unless what they're trying to do isn't possible.

2020-02-05 11:27 UTC, pop4959 commented
fair enough

2020-02-11 12:32 UTC, mdcfe requested changes

2020-02-11 12:32 UTC, md678685 commented on Essentials/src/kits.yml
> +      - /ebc {PLAYER} just got some fancy tools!
```suggestion
      - /broadcast {PLAYER} just got some fancy tools!
```

2020-02-11 14:38 UTC, JasonHorkles commented
Do I actually have to change anything or is it good with what you did? No idea what I'm doing 😂

2020-02-11 16:05 UTC, md678685 commented
You need to commit the suggestion for it to become part of the PR (I'd do it but I don't have access to a PC right now).

2020-02-11 19:26 UTC, pop4959 approved these changes

2020-02-16 15:39 UTC, mdcfe approved these changes

2020-02-16 15:39 UTC, merged