send-info-after-death
EssentialsX/Essentials pull request #3032
Opened 2020-02-24 01:16 UTC by kakd

A possibly fixed version of https://github.com/EssentialsX/Essentials/pull/2912. I'm not very skilled in coding, but here's my best shot on making the suggested changes. I couldn't have done this without seeing the PR from @darbyjack . I'm not sure if this is the standard way of modifying a PR, sorry if it's not.

2020-02-24 01:33 UTC, pop4959 approved these changes

2020-02-24 01:34 UTC, pop4959 commented
I don't know if there is a convenient way to modify other people's pull requests without being a project maintainer. This is probably fine, but I think @darbyjack should at least have a chance to take a look at this since he has the original pull request still open.

As far as I can tell, it seems all of the suggested fixes were applied appropriately though. Looks good.

2020-02-24 01:37 UTC, kakd commented
Thanks pop! Could you help me understand something? Why did the check fail for me when it passed for the other PR? Also, how come you approved the changes even though the check failed?

2020-02-24 01:47 UTC, pop4959 commented
@kakd The build failed because Spigot added new methods to interfaces which Essentials is using in some of its implementation / testing framework. If you look at the details of the build you will see this:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project EssentialsX: Compilation failure
[ERROR] /home/runner/work/Essentials/Essentials/Essentials/src/com/earth2me/essentials/OfflinePlayer.java:[41,8] com.earth2me.essentials.OfflinePlayer is not abstract and does not override abstract method swingOffHand() in org.bukkit.entity.LivingEntity
```
Someone will just have to run a re-build of this PR once those methods are added. Nothing needed on your part.

2020-03-05 05:29 UTC, pop4959 commented
@kakd Build fails for a new reason now. Apparently it isn't able to check out from your repo anymore. I'm not sure why that would be the case but you should probably check on that.

```
reference is not a tree: b87981a785670f5daf6f5b8308dbf998206d0996
Git checkout failed with exit code: 128
```

2020-03-31 05:44 UTC, Ichbinjoe requested changes

2020-03-31 05:44 UTC, Ichbinjoe commented on Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java
> +            user.sendMessage(tl("infoAfterDeath", loc.getWorld(), loc.getBlockX(), loc.getBlockY(), loc.getBlockZ()));
This should be log.getWorld().getName or something like that

2020-04-20 06:41 UTC, SrBedrock commented
@kakd

2020-04-30 13:38 UTC, darbyjack commented
Closing this one as you've recreated a new one.

2020-04-30 13:38 UTC, closed without merging