Near exclude permission
EssentialsX/Essentials pull request #3049
Opened 2020-03-05 07:25 UTC by pop4959

Closes #2916. 

Simple addition. LuckPerms 5 seems to support the defaults well too.

2020-03-15 23:46 UTC, JasonHorkles submitted a review, later dismissed

2020-03-29 20:37 UTC, JRoy requested changes

2020-03-29 20:37 UTC, JRoy commented on Essentials/src/com/earth2me/essentials/commands/Commandnear.java
> +            if (!player.equals(user) && !player.getBase().hasPermission("essentials.near.exclude") && (!player.isHidden(user.getBase()) || showHidden || user.getBase().canSee(player.getBase()))) {
Should use `player.isAuthorized("essentials.near.exclude")` right?

2020-03-29 20:48 UTC, JRoy approved these changes

2020-03-29 20:53 UTC, pop4959 commented
May need to be re-tested to see if the default permissions still work as intended. I don't think they should, but I've seen stranger things happen. I know Essentials has issues when it comes to default permissions with other checks, so I wonder if hasPermission vs isAuthorized actually behave differently.

2020-03-31 05:47 UTC, Ichbinjoe approved these changes

2020-03-31 05:47 UTC, merged