Add passenger dismounting for teleports
EssentialsX/Essentials pull request #3069
Opened 2020-03-13 15:20 UTC by JRoy

Adds a `teleport-passenger-dismount` config option (true by default) which will dismount all the player's passengers before teleporting the player. This is needed as a player cannot teleport with a passenger.

Closes #2087

2020-03-13 20:02 UTC, pop4959 requested changes

2020-03-13 20:02 UTC, pop4959 commented on Essentials/src/messages.properties
> +passengerTeleportFail=\u00a74Teleporting requires no passengers and teleport-passenger-dismount is disabled.
This doesn't seem to be a very player-friendly message. It seems to be geared more towards server admins. I think the description of the setting should be solely in the config. Maybe change this to something like "You cannot teleport while carrying passengers." or something like that.

2020-03-13 20:05 UTC, pop4959 commented
In addition to the comment above, I'm not sure if the PR covers all cases. I don't think you can teleport while being a passenger either, but it doesn't seem like the code checks for that. Maybe you can test this to make sure, in case I'm wrong.

Case 1: the player has passengers
`getPassengers().leaveVehicle()`
Case 2: the player is a passenger
`getVehicle().eject()`

2020-03-13 21:15 UTC, JRoy commented
@pop4959 Changes applied!

As for if the player is riding an entity, I've just tested it and the player can be properly teleported if they are riding an entity so no need for that second check.

2020-03-13 21:52 UTC, pop4959 submitted a review, later dismissed

2020-03-31 06:47 UTC, Ichbinjoe submitted a review, later dismissed

2020-03-31 19:10 UTC, JRoy commented
@Ichbinjoe why was this labeled as waiting on author?

2020-03-31 20:58 UTC, Ichbinjoe commented
Conflicts.

2020-03-31 23:03 UTC, JRoy commented
Took way longer than it should've but successfully rebased 😂

2020-04-01 00:01 UTC, pop4959 approved these changes

2020-04-01 01:03 UTC, Ichbinjoe approved these changes

2020-04-01 01:04 UTC, merged

2020-04-04 14:50 UTC, triagonal commented
This breaks teleports on versions below 1.11.2, as `Entity#getPassengers` didn't exist until this version.

2020-04-04 14:53 UTC, JRoy commented
Fixing momentarily