Add UUID and User based economy methods
EssentialsX/Essentials pull request #3085
Opened 2020-03-22 21:21 UTC by JRoy

Adds methods to the Economy API to use UUIDs and User objects. Additionally, deprecates all the username (String) based methods

2020-03-27 02:45 UTC, squidicuzz submitted a review, later dismissed
I agree that fetching the economy user on all calls with `getUserByName()` should assure that legacy lookup or non-players are loaded before making any balance changes.  This might resolve intermittent issues with balances corruption if the lookup failed due to not being loaded for some reason.
Looks good.

2020-03-31 07:11 UTC, Ichbinjoe requested changes

2020-03-31 07:11 UTC, Ichbinjoe commented on Essentials/src/com/earth2me/essentials/api/Economy.java
> +            throw new RuntimeException("Economy uuid cannot be null");
Don't use RuntimeException for this. IllegalArgumentException is a far better choice.

2020-03-31 07:11 UTC, Ichbinjoe commented on Essentials/src/com/earth2me/essentials/api/Economy.java
> +            throw new RuntimeException("Economy user cannot be null");
IllegalArgumentException

2020-03-31 07:11 UTC, Ichbinjoe commented on Essentials/src/com/earth2me/essentials/api/Economy.java
> +     * @throws NoLoanPermittedException  If the user is now allowed to have a negative balance
user is *not* allowed

2020-03-31 07:11 UTC, Ichbinjoe commented on Essentials/src/com/earth2me/essentials/api/Economy.java
> +     * @throws NoLoanPermittedException  If the user is now allowed to have a negative balance
*not*

2020-03-31 07:11 UTC, Ichbinjoe commented on Essentials/src/com/earth2me/essentials/api/Economy.java
> +     * @param amount The money you want to add
Consider rewording all around to something more like 'The amount of money to be added to the user's account'

2020-03-31 15:36 UTC, JRoy commented
Changes applied!

2020-04-13 13:07 UTC, mdcfe submitted a review, later dismissed

2020-04-13 13:07 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/api/Economy.java
> +     * @throws NoLoanPermittedException  If the user is now allowed to have a negative balance
@JRoy Is this fixed?

2020-04-13 14:08 UTC, JRoy commented on Essentials/src/com/earth2me/essentials/api/Economy.java
> +     * @throws NoLoanPermittedException  If the user is now allowed to have a negative balance
@md678685 it is now :P

2020-04-13 14:49 UTC, mdcfe submitted a review, later dismissed

2020-05-02 18:37 UTC, JRoy commented
@md678685 Backwards compatibility has been maintained and I added User validation to UUID-based methods and null checks in User-based methods

2020-05-04 09:58 UTC, mdcfe approved these changes

2020-05-04 10:00 UTC, merged