Proper command alias
EssentialsX/Essentials pull request #3101
Opened 2020-03-28 16:17 UTC by NoahH99

2020-03-28 17:26 UTC, JRoy commented
IMO just add `ecreative` as another alias. This way if someone is using `eecreative` in some type of automated workflow, that doesn't break.

2020-04-09 15:25 UTC, mdcfe requested changes

2020-04-09 15:25 UTC, md678685 commented on Essentials/src/plugin.yml
> +    aliases: [adventure,eadventure,adventuremode,eadventuremode,creative,ecreative,creativemode,ecreativemode,egamemode,gm,egm,gma,egma,gmc,egmc,gms,egms,gmt,egmt,survival,esurvival,survivalmode,esur
```suggestion
    aliases: [adventure,eadventure,adventuremode,eadventuremode,creative,ecreative,eecreative,creativemode,ecreativemode,egamemode,gm,egm,gma,egma,gmc,egmc,gms,egms,gmt,egmt,survival,esurvival,survivalmode,esurvivalmode,gmsp,sp,egmsp,spec,spectator]
```

2020-04-14 16:29 UTC, mdcfe approved these changes

2020-04-14 16:30 UTC, merged