Added real name boolean option for the /list command
EssentialsX/Essentials pull request #3117
Opened 2020-04-01 08:37 UTC by Radoje17

2020-04-01 09:07 UTC, pop4959 requested changes
Appears to be functionally correct, but there are a few minor points to improve upon. It would also be nice to see a screenshot of how this option appears in-game (with both display names only, with username, and both mixed).

2020-04-01 09:07 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/ISettings.java
> -
Why did you delete a line randomly here?

2020-04-01 09:07 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/PlayerList.java
> +                groupString.append(user.getDisplayName());
Better: append this unconditionally, and only append the other part based on the condition.

2020-04-01 09:07 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/Settings.java
> +import java.util.*;
Please don't do this! I know the IDE will do this automatically, but you can turn it off. Wildcards are great in some cases, but I don't think this is one of them.

2020-04-01 09:07 UTC, pop4959 commented on Essentials/src/config.yml
> +real-names-on-list: false
Every config option should have a description. What's clear to you may not be for others.

2020-04-01 09:19 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/PlayerList.java
> +                groupString.append(user.getDisplayName());
Oh also on second thought, you should also be using append instead of concatenation.

2020-04-01 10:59 UTC, Radoje17 reviewed
Screenshots:
![image](https://user-images.githubusercontent.com/33990494/78129665-39718700-7418-11ea-826b-dee0352c4cd7.png)
![image](https://user-images.githubusercontent.com/33990494/78129721-51e1a180-7418-11ea-8d37-fbce11daea6d.png)
![image](https://user-images.githubusercontent.com/33990494/78129910-9cfbb480-7418-11ea-9e66-0ec80e6219fa.png)

2020-04-01 11:01 UTC, Radoje17 reviewed
Missed one parenthesis

2020-04-01 21:33 UTC, pop4959 requested changes
Thanks for giving some screenshots of your test cases, that looks good to me!

I still found a few minor things to nitpick on, but they aren't difficult to fix and then this PR will be perfect!

2020-04-01 21:33 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/PlayerList.java
> +
Looks like you added extra space here for whatever reason

2020-04-01 21:33 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/PlayerList.java
> +                groupString.append(" (");
Might look cleaner if you chain append calls (this is common for StringBuilder; example: `.append("a").append(b)` -> `"ab"`).

2020-04-01 21:33 UTC, pop4959 commented on Essentials/src/config.yml
> +# Show realnames on /list if player has a nickname
I think this should still be clarified a bit more. Maybe something like:

"Displays real names in /list next to players who are using a nickname."

2020-04-02 06:37 UTC, Radoje17 reviewed
Fixed

2020-04-02 07:02 UTC, pop4959 approved these changes

2020-04-02 07:06 UTC, merged