Pay toggle per player. Fixes #3087
EssentialsX/Essentials pull request #3168
Opened 2020-04-15 05:15 UTC by TreyRuffy

Allows the player to do /paytoggle <player> to only toggle pay for that single player

2020-04-15 05:21 UTC, TreyRuffy commented
This is for #3087. Tell me if there's anything I overlooked, and I should be able to fix it.

2020-04-15 07:26 UTC, pop4959 requested changes
Not a full review, but a few comments to get you started. Also feels like you could clean this up a bit more.

2020-04-15 07:26 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/User.java
> +        return this.isAuthorized("essentials.paytoggle.exempt");
Is this necessary? You're only checking the permission once, in the command.

2020-04-15 07:26 UTC, pop4959 commented on Essentials/src/messages_en.properties
> +noPayBlocked=§6You are not blocking anyone''s pay.
Messages should be in messages.properties only, as the localized versions will be overwritten by Crowdin.

2020-04-15 07:26 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandpaytoggle.java
> +            if (args[0].equalsIgnoreCase("players")) {
I don't see why this list feature is necessary. Why not just tell the player when the payment is going through that it's blocked?

2020-04-15 07:26 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandpaytoggle.java
> +                    player = getPlayer(server, args, 0, true, true);
getPlayer already gets offline players, this try/catch thing isn't necessary.

2020-04-15 07:26 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandpaytoggle.java
> +                    throw new PlayerNotFoundException();
Don't catch and re-throw this. If getPlayer doesn't find it, just let it throw itself.

2020-04-22 15:37 UTC, md678685 commented
This PR has nothing to do with #3087. As far as I can tell, #3087 is asking for `/paytoggle` to function as a `EssentialsToggleCommand` like `/msgtoggle` and `/vanish`, which is reasonable (not sure why it wasn't implemented this way in the first place).

In contrast, this PR adds a secondary function to `/paytoggle` that allows players to block specific players from `/pay`. I'm not sure what the use case for this feature is? `/pay` could just be designed to respect `/ignore`, which would be a lot less convoluted as that way players don't need to manage several block lists.

2020-05-27 06:57 UTC, pop4959 commented
Closing this in favor of #3273, as it seems this PR is inactive

2020-05-27 06:57 UTC, closed without merging