Replace UserTeleportEvent with more sane events
EssentialsX/Essentials pull request #3192
Opened 2020-04-23 16:26 UTC by md678685

**NOTE: this PR is a draft and won't be ready for merge until after #3102 is merged.**

This PR replaces UserTeleportEvent with two new teleport events called at different stages:
- TeleportWarmupEvent; called before a user's teleport warmup begins and allows plugins to skip it or prevent a teleportation
- PreTeleportEvent; called after the warmup completes but before any safety checks are carried out

This is a breaking change as it removes UserTeleportEvent, but the previous event isn't useful or descriptive in its current form and was only recently introduced, so it's unlikely that many plugins already depend on this.

Closes #2506.

2020-04-23 16:29 UTC, JRoy commented
*cries in async pr conflicts*

2020-07-08 08:07 UTC, pop4959 approved these changes

2020-07-08 13:31 UTC, JRoy requested changes
PR looks fine but I do think a cause enum should be in the TeleportWarmupEvent to address requests like #3401

2020-07-08 18:12 UTC, md678685 commented
@JRoy Adding a cause enum here doesn't necessarily address #3401 - #3403 solves this better.

2020-07-08 18:14 UTC, JRoy approved these changes

2020-07-08 18:51 UTC, merged