send-info-after-death
EssentialsX/Essentials pull request #3207
Opened 2020-04-29 07:54 UTC by kakd

I think I know what caused the problem with #3032, but I couldn't figure out how to fix it without making a new pull request, so here's that.

Closes #2896

2020-05-19 13:06 UTC, mdcfe requested changes
Looks good aside from one comment.

2020-05-19 13:06 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/EssentialsEntityListener.java
> +            user.sendMessage(tl("infoAfterDeath", loc.getWorld().getName(), loc.getBlockX(), loc.getBlockY(), loc.getBlockZ()));
This is a tiny nitpick but IMO we should send this message *before* the `/back` message, rather than after it.

2020-05-27 06:50 UTC, pop4959 approved these changes

2020-05-27 08:57 UTC, mdcfe approved these changes

2020-05-27 08:58 UTC, merged