Hiding deathmessage in vanish.
EssentialsX/Essentials pull request #3255
Opened 2020-05-10 18:14 UTC by Destitution-SC

Hides your death message if you're in vanish to prevent exposing yourself.

2020-05-11 16:04 UTC, mdcfe requested changes
This PR currently doesn't compile.

2020-05-11 16:04 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
> +    public void onPlayerDeath(final PlayerDeathEvent event) {
You need to import the event

2020-05-14 00:04 UTC, YanisBft submitted a review, later dismissed

2020-05-19 14:13 UTC, mdcfe requested changes

2020-05-19 14:13 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
> +        if(user.isVanished()) {
```suggestion
        if (user.isVanished()) {
```

2020-06-15 13:10 UTC, mdcfe requested changes
IMO this should be behind a config option. Some people might want to give people vanish without keeping vanished players a complete secret.

2020-06-19 16:43 UTC, JRoy reviewed
Agree with @md678685, needs a config option

2020-06-19 16:43 UTC, JRoy commented on Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
> +        final User user = ess.getUser((Player) event.getEntity());
Why is there a cast here, it's already a player.

2020-06-19 19:08 UTC, pop4959 commented
I would suggest instead adding a permission that shows the death message (when negated, it hides it). This creates a more robust and generalized solution, where the death messages can be conditionally hidden, and for vanish, you would only need something like the following:
`/lp group default permission set essentials.showdeathmessage false essentials:vanished=true`

2020-07-24 08:09 UTC, pop4959 commented
Closing due to author inactivity. Can re-open if there are signs of life, especially addressing any concerns that have been mentioned.

2020-07-24 08:09 UTC, closed without merging