Fix clearing specific items in clearinventory
EssentialsX/Essentials pull request #3263
Opened 2020-05-12 04:16 UTC by pop4959

Fixes #2986
Closes #3050
Closes #3191

Refactors the clearinventory command code in such a way that fixes the problem of not being able to clear all of a specific item on newer server versions. Also re-adds data value support for older server versions that support it, which seemed to have been inadvertently removed in 79bc34047b86461e752491d08ee8a38a5c07d9dd.

Checked against 1.8.8, 1.12.2, 1.13.2, 1.15.2.

2020-05-12 04:40 UTC, darbyjack submitted a review, later dismissed

2020-05-12 19:35 UTC, JRoy submitted a review, later dismissed

2020-05-13 10:06 UTC, mdcfe requested changes

2020-05-13 10:06 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/commands/Commandclearinventory.java
>          int type = -1;
I'd prefer this was replaced with a private enum, as done in #3191 - this variable only exists to control flow later on, and it's clearer if it uses a named enum constant than a magic number.

2020-05-13 22:18 UTC, JRoy approved these changes

2020-05-17 20:09 UTC, mdcfe approved these changes

2020-05-17 20:10 UTC, merged

2020-06-15 19:11 UTC, UnrealPixel commented
Clearing items with custom names still does not work properly?

2020-06-15 19:18 UTC, md678685 commented
@UnrealPixel Named items are not supported by `/clear`.

2020-06-15 19:23 UTC, UnrealPixel commented
> @UnrealPixel Named items are not supported by `/clear`.
How to clear custom named items?

2020-06-15 19:35 UTC, UnrealPixel commented
@md678685 Then how do I clear items with a name?

2020-06-15 19:49 UTC, pop4959 commented
@UnrealPixel The bug that was fixed in this PR was that you could not clear *specific* items (as in, only dirt), only the whole inventory, whereas in the past this was possible.

You should be able to use [/minecraft:clear](https://minecraft.gamepedia.com/Commands/clear) for removing items with specific NBT tags. The Essentials command is not designed to be so advanced.

2020-06-15 19:58 UTC, UnrealPixel commented
@pop4959 That is why I reopened #592 which was closed because this was the "same" issue.
when I do: /minecraft:clear @p rotten_flesh 0 1 {display:{Name:&8Scraps}} it doesn't clear the rotten flesh with the name Scraps in Gray.