Clean up providers a bit
EssentialsX/Essentials pull request #3279
Opened 2020-05-14 07:51 UTC by pop4959

This PR doesn't really change any functionality in the providers, I just wanted to clean stuff up a little bit.

Removed the `providerType` string in the `ProviderFactory` constructor in favor of a new `getType` method in Provider which replaces the old `getHumanName` method. The idea behind this is because it seems a bit silly to pass the string in the constructor and the providers themselves should be able to keep track of what type they are. The `getHumanName` method was also itself not very helpful as it returns a hard coded string, and so it's hard to tell which class the provider is based on.

This is only really apparent in the startup log so here's how it looks:

Old
```
[00:19:58 INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[00:19:58 INFO]: [Essentials] Using 1.13+ flat spawn egg provider as spawn egg provider.
[00:19:58 INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
```

New
```
[00:21:15 INFO]: [Essentials] Using BlockMetaSpawnerProvider as Mob Spawner provider.
[00:21:15 INFO]: [Essentials] Using FlatSpawnEggProvider as Spawn Egg provider.
[00:21:15 INFO]: [Essentials] Using BasePotionDataProvider as Potion Meta provider.
```

As you can see, not much different, but I think just simply printing the class name of the provider is less ambiguous.

Also ran IntelliJ's formatter over the files and it found a couple things.

2020-05-14 19:01 UTC, darbyjack submitted a review, later dismissed
👍

2020-05-14 19:03 UTC, JRoy submitted a review, later dismissed

2020-05-19 13:04 UTC, mdcfe requested changes
I'm not sure about removing the human name - they describe the intent of each implementation (which NMS/OBC/Bukkit APIs they were designed to use, what versions they were intended for etc.). We could keep the human name and add the class name to the startup message in addition (perhaps `Using 1.8.3 BlockStateMeta provider (BlockMetaSpawnerProvider) [...]`). If we're going to remove the human name for each provider implementation, it might be worth adding a comment to each class with that information instead. I feel the current names for some of the providers are poor since they don't really explain why they exist or what versions they were intended for (what's "legacy"? what does the "Reflection based" one do?), so those descriptions could also be improved somewhat.

2020-05-19 23:24 UTC, pop4959 commented
@md678685 I was a bit hesitant at first about removing the method from the interface but I really don't see it's usefulness. As you said, it's mostly intended to describe the intent of each implementation, although this could just as easily done in a comment rather than code. Otherwise, its only purpose was to be shown to users as an "easy to understand" name in console, although I think the names that are given are confusing anyway (I'd much rather look at the `providerType` string to understand what it's for).

For example, "1.8.3+ BlockStateMeta provider" means absolutely nothing to a user. What is a "BlockStateMeta"? This is obviously an implementation specific description, which isn't helpful to understand. On the other hand, "mob spawner provider" is a bit more easily digestible. I may not know what a "provider" is, but assuming I've played a fair bit of Minecraft, I sure do know what a "mob spawner" is, and this gives me a better idea of what Essentials is trying to set up compatibility for. Lastly, the hard coded version string just purely adds confusion. Sure, the provider may be intended or designed to run on specific versions, however since the design of the ProviderFactory is to return the first provider that works on the current server implementation, there is no guarantee that the intended provider will be chosen for a particular version of Minecraft or server implementation. With the previous example, "1.8.3+ BlockStateMeta provider" is *intended* to run on a server running Minecraft 1.8.3 or above, right? Well, in reality it's used on 1.13.0-1.15.2 which is far removed. LegacySpawnerProvider is what is *actually* loaded and used currently on 1.8.0-1.12.2 (which is also why we removed the 1.8 R1 and R2 providers).

Hopefully with the above example you can understand a bit more why I wanted to get rid of this the `getHumanName` method. I'm not sure if the new `getType` method is a good solution to it, but I think it's at the very least better. Instead of writing a hard coded string in each base provider class, the type can just be declared in the `getType` method once, for each abstract class. Alternatively we could generate the type name based on the abstract class name and return that as a string (which avoids the extra enum). I'm open to any ideas that could be better than this.

I wouldn't mind adding documentation to some of the existing providers if this helps as well. Some of the class names *sort of* make sense after looking into the implementations a bit. Most of the provider classes are named after what kind of API or implementation method they use currently. For example, the `Legacy` classes all implement things based on item data/durability/ids, which were used in all old versions of Minecraft prior to 1.13. The `Reflection` provider (I believe there's only one currently) is effectively using NMS/OBC through reflection. It could probably be more clear what kind of reflection it is doing, especially if more reflection based providers are added. I think that all future providers that deal with NMS/OBC should be implemented via reflection in order to avoid compile dependencies on the server, so it might be good to start naming these appropriately. I didn't want to rename them in this PR because I thought that was worth an extra discussion later. I could do it in this PR as well though if we want to discuss it now.

2020-05-20 19:37 UTC, mdcfe submitted a review, later dismissed

2020-05-28 19:01 UTC, mdcfe approved these changes

2020-05-28 19:06 UTC, merged