Update command for eco reset
EssentialsX/Essentials pull request #3300
Opened 2020-05-17 01:45 UTC by Destitution-SC

Fixes issue #3251

2020-05-17 02:24 UTC, pop4959 requested changes
In addition to the comments, can you show that you have tested it (command(s) used + screenshot(s) are good enough).

2020-05-17 02:24 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandeco.java
> -
Undo this diff to keep consistent style with other ess code

2020-05-17 02:24 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandeco.java
> +
=

2020-05-17 02:24 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandeco.java
> +        player.sendMessage(tl("resetBalSelf", startingBalance.toString()));
Should probably be using NumberUtil::displayCurrency here

2020-05-17 02:24 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandeco.java
> +            sender.sendMessage(tl("resetBalOther", player.getDisplayName(), startingBalance.toString()));
=

2020-05-17 02:26 UTC, pop4959 commented
Oh also it might be good to change the usage for eco in the plugin.yml file to indicate that the amount argument is optional.

2020-05-17 12:51 UTC, Destitution-SC commented
Welp it doesn't work it keeps returining the usage. :(
I can a bit code but im not really experienced. So can anyone else help?

2020-05-19 09:55 UTC, imDaniX commented
Can't we just do something like this?
```java
            case RESET:
                amount = ess.getSettings().getStartingBalance();

            case SET:
                set(amount, player, sender);
                break;
```
So we don't have to create new tr strings.
Also, `/eco reset` is a part of `/eco`, so I'm not sure how it supposed to look like because it will change other parts of the command.
Maybe `/<command> <give|take|set|reset> <player> [amount]`, but it's not really good.

2020-05-22 08:08 UTC, pop4959 requested changes
Sorry for the long delay in reviewing your PR, I've been more busy lately. Someone recently suggested an implementation for this fix which may be simpler, which is to simply set the `amount` to the configured starting balance in the reset command, rather than writing a lot of extra logic (especially since a lot of it ends up being similar, and involves more translation). Maybe give it a try.

As for your question, it is probably returning the usage because the command still expects  (as is checking) that all 3 arguments are passed in. You might have to add an exception to that for reset.

If you need help answering any other questions let me know.

2020-05-22 08:08 UTC, pop4959 commented on Essentials/src/plugin.yml
> +    usage: /<command> [give|take|set|reset] [player] <amount>
Original was correct, no need for change here. The angle brackets (by common convention) indicate *required* arguments, while square brackets indicate *optional* arguments. In this command, the first two arguments are required, however the third can be optional. So you actually want to flip this here.

2020-05-22 11:02 UTC, Destitution-SC commented
![Screenshot_1](https://user-images.githubusercontent.com/43219594/82661480-62e6ac00-9c2c-11ea-958f-ffe34eaa1eac.png) I'm pretty sure these are the errors returning the usage but no idea on how to fix that error with try and catch thing.

2020-05-28 07:36 UTC, pop4959 commented
Hey @Destitution-SC, thanks for all of the effort you put in here. I decided I'd help you out and take a look at the issue myself, and it looks like the fix is actually quite easy. Check out #3340. So, the solution is just to short circuit evaluate `isPercent` in a similar manner to `amount`, because the problem is with accessing `args[2]` when there is no third argument present (which is the case when reset is run). 😄

2020-05-28 18:44 UTC, closed without merging