Allow ability to use /whois for offline users
EssentialsX/Essentials pull request #3301
Opened 2020-05-17 03:45 UTC by JRoy

2020-05-17 09:27 UTC, pop4959 requested changes
Looks pretty good overall to me. One thing I don't agree with though is adding an online/offline time to whois, because the seen command is already entirely designated to handling that specific task.

Also it wasn't explicitly clear what was wished for in the feature request, but this doesn't actually get all of the information that whois normally returns to the user. It shows what it can, which is still probably better than denying the command entirely for offline players.

Online

![image](https://user-images.githubusercontent.com/17698576/82140747-d11f0f00-97e5-11ea-8535-d06eba14dae9.png)

Offline

![image](https://user-images.githubusercontent.com/17698576/82140748-d5e3c300-97e5-11ea-8e37-6affbcf03bb4.png)

2020-05-17 09:27 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandwhois.java
> +        catch (IllegalArgumentException ignored) {
This code (and any that follow similarly) should be placed on the same line of code as the bracket to stay consistent with ess code style

2020-05-17 10:42 UTC, Destitution-SC commented
You could also add the mute/ban info to offline players for /whois

2020-05-17 15:50 UTC, JRoy commented
@pop4959 Changes applied

2020-05-18 14:27 UTC, darbyjack approved these changes

2020-05-18 14:28 UTC, darbyjack submitted a review, later dismissed
Just tested this locally and it looks to be working fine. This is a great feature to be implemented. Thanks for doing this!

2020-05-27 08:14 UTC, pop4959 requested changes
Just remove the online/offline text entirely -- it's not useful, as this is pretty obvious information, and it adds extra clutter.

Also, I'm not really sure if I agree with adding ban information to this command, as this duplicates even more behavior of `/seen`.

On the whole, the more I think about this issue the more I think this information should be put into `/seen` instead of `/whois`. It's basically the same command, except with the intent for being used to view information on offline players. Especially since half of the information in `/whois` doesn't even apply to offline users, this would make more sense and be less confusing in my opinion.

2020-05-27 12:29 UTC, JRoy commented
@pop4959 As for ban information: the whois command already displays mute information so I felt that kind of fit. As for seen vs whois, you're right there is an information overlap. Let me look into that further

2020-06-08 20:21 UTC, pop4959 commented
> As for ban information: the whois command already displays mute information so I felt that kind of fit. As for seen vs whois, you're right there is an information overlap. Let me look into that further

That wasn't really my point there. If `/whois`' functionality is extended to support offline players as well, then of course it does make sense for it to show this sort of information. But remember that this command was, before this PR, not intended to be used by offline players.

The issue that is linked doesn't really elaborate on what they mean by offline whois, but if you want to be pedantic, it means that **all** functionality of whois should be available for offline players, which this PR **does not** do. While obviously having everything is likely not feasible to do currently due to limitations in the API, I don't think providing a half working implementation is the right way to go. It's just begging for further confusion, and further disappointment from people who want to see the information that is not shown.

If you read in between the lines, what probably makes more sense is to add additional information to `/seen` instead, which is the corresponding command for looking up offline players. This way, whois doesn't need to be muddied up with a half working offline implementation, but instead seen can show just the information that is relevant to offline players.

2020-06-22 19:15 UTC, pop4959 requested changes
I still think this should be better implemented by enhancing `/seen`. I might be willing to do this myself at some point.

2020-06-22 19:16 UTC, JRoy commented
@pop4959 feel free, i'm not sure how i wanted to do this, you have push perms on my fork

2020-06-22 19:23 UTC, pop4959 commented
I'm not sure either, but it might be good to add with #3362 as well. Also worth asking on #1766 what they actually wanted out of this, so I've done that.

2020-10-11 20:19 UTC, closed without merging