Add UserTeleportHomeEvent
EssentialsX/Essentials pull request #3306
Opened 2020-05-19 15:25 UTC by kmecpp

This PR adds an event that gets called when a player teleports to their home but before the world is resolved (which immediately throws an InvalidWorldException if the world isn't current loaded).

This allows servers to intercept home teleports and load worlds that may be unloaded when a player tries to teleport to them

2020-05-19 21:48 UTC, pop4959 requested changes
I don't like the implementation of this PR in its current state. `UserTeleportHomeEvent` is, for the most part, a duplicate of the `UserTeleportEvent` which already exists. Part of the problem is `LocationData` which is also effectively a duplicate of `Location` in the Bukkit API. This definitely needs to be cleaned up if it's going to be considered as an Essentials API addition.

Since all of this seems to be just to bypass the `InvalidWorldException`, I'm not sure that this is worth all the effort. Perhaps for your niche use case, you can simply use `PlayerCommandPreprocessEvent` to catch home commands before they're executed, and read the world from the user data file to check that it's a world which is loaded.

2020-05-20 02:16 UTC, kmecpp commented
I don't believe there's currently any reliable way to do that. The current User.getHome(String) method will throw an InvalidWorldException if the world isn't loaded.

The only way I see right now would be to access the user's config data with reflection and manually parse their home names and locations from the internal config data which.

Do you have any suggestions?

2020-05-25 10:32 UTC, md678685 commented
Out of interest, what's your use case for dynamically loading/unloading worlds that users have homes in? My instinct tells me that this feels like convoluted API bloat, and I can't think of a good instance where you'd want to dynamically load worlds, rather than keeping them loaded and idle.

2020-05-28 22:07 UTC, kmecpp commented
My current use case is trying to seamlessly integrate two survival servers on a bungee network. I would like users to be able to use /home even if their homes are located on another server.

Regarding just loading all worlds, I have around 35 worlds on one of my servers so keeping them all loaded has 1) a small but significant impact on performance and 2) also makes server management and using commands like /gc far more annoying to use as you can probably imagine.

Another one of my servers also has a feature where each player can get access their own separate world. Yes I could load everyone's world when they login, but having 50 players on and only 3 of them using their separate world is obviously far from ideal.

Additionally on modded servers certain mod world often can't really be managed well by plugins so loading everything isn't always an option. Obviously you guys don't support modded servers but it's just another point to consider.

2020-06-01 11:48 UTC, md678685 commented
> [...] trying to seamlessly integrate two survival servers on a bungee network. I would like users to be able to use /home even if their homes are located on another server.

The event added in this PR doesn't appear to be relevant to this use case - it exposes the data of a home after EssentialsX has already resolved the home's name to a location.

I'd recommend adding a `/home` command on the BungeeCord side, and using a plugin on the Bukkit side to send the list of available home names to Bungee and perform teleports as needed. There are a few existing solutions for this, but you can roll your own fairly easily using the existing EssentialsX APIs on the Bukkit side along with plugin messages/a message queue/Redis/etc to communicate with the proxy.

> Regarding just loading all worlds, [...] keeping them all loaded has 1) a small but significant impact on performance [...] Another one of my servers also has a feature where each player can get access their own separate world. 

Bukkit has methods to disable keeping spawn areas loaded and to remove any force-loaded chunks, and these should collectively minimise the impact of keeping worlds loaded.

> on modded servers certain mod world often can't really be managed well by plugins 

You answered it yourself - we don't provide any support or guarantee any level of compatibility with hybrid servers. It's up to whoever maintains the hybrid server you use to provide compatibility between Bukkit worlds and modded dimensions, and these hybrid servers rarely bother to make Bukkit plugins and Forge mods work properly. For this reason, mod support is not a concern at all for EssentialsX.

---

I appreciate the time taken to make this PR, but this is neither an ideal solution to your problem nor something we're willing to promote as an API right now. What you're trying to achieve feels far beyond what EssentialsX's current homes system was designed for, and this PR feels like a quick hack rather than a proper API design. Bukkit just isn't designed in a way for plugins to play nice with dynamic world unloading, and any plugin that tries to construct a `Location` from a world that isn't loaded will face the same problems as EssentialsX does here. In the future, we may refactor the homes/warps system with a custom destination API, but this PR is too limited for this purpose.

2020-06-01 11:48 UTC, closed without merging

2020-06-05 12:27 UTC, kmecpp commented
Would it at least be reasonable to expose player's home locations through the API?

2020-06-05 18:58 UTC, pop4959 commented
That's the job of the getHome methods which you have a problem with. You'll probably just need to read the userdata file yourself for now.