Add getName method to ItemResolvers for custom serialization
EssentialsX/Essentials pull request #3307
Opened 2020-05-19 15:37 UTC by md678685

Add an optional `getName` method to `ItemResolver`s which plugins can implement in order to add custom items to `/createkit`.

Closes #3305, closes #3216.

2020-05-19 21:19 UTC, pop4959 requested changes

2020-05-19 21:19 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/items/AbstractItemDb.java
> +    ItemStack tryRevolverDeserialize(String id) {
You probably meant `Resolver` here and not `Revolver` 🔫

2020-05-19 21:19 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/items/AbstractItemDb.java
> +    String tryRevolverSerialize(ItemStack stack) {
=

2020-05-19 21:23 UTC, pop4959 commented
The changes look good, although I think `getName` may be a bit confusing. Maybe something along the lines of `getCustomName` or `getStackIdentifier` would be more clear, since `getName` is never used for normal items? Just an idea, but maybe I don't fully understand this.

2020-05-20 10:01 UTC, md678685 commented
In retrospect `serialize` is probably a better name for this method than `getName`.

2020-05-27 04:29 UTC, pop4959 approved these changes

2020-06-15 12:46 UTC, merged