Add itemlore command
EssentialsX/Essentials pull request #3331
Opened 2020-05-25 06:42 UTC by JRoy

Adds a command to add to or clear an items lore.

Closes #1911

2020-06-06 17:16 UTC, md678685 commented
It might be useful to allow users to modify or remove specific lines too, so they don't need to wipe the lore and start over.

2020-06-08 22:51 UTC, pop4959 requested changes
I tried out the command, and I like it, but setting a specific line's lore doesn't seem to work.

To replicate this, add several lines of lore, such as `/itemlore add a` three times. Then, try something like `/itemlore set 1 b`, and notice that the text doesn't change.

2020-06-12 01:33 UTC, JRoy commented
mfw 
![image](https://user-images.githubusercontent.com/10731363/84455353-1ee33780-ac2b-11ea-9940-260544db6cd4.png)

2020-06-15 09:00 UTC, pop4959 requested changes

2020-06-15 09:00 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commanditemlore.java
> +            return;
```suggestion
            throw new Exception(tl("itemloreInvalidItem"));
```
This is probably better, to remain consistent with the way you are handling errors in other parts of this command.

2020-06-15 14:42 UTC, JRoy commented
@pop4959 changes applied

2020-06-16 00:55 UTC, pop4959 submitted a review, later dismissed

2020-06-22 19:12 UTC, pop4959 submitted a review, later dismissed

2020-07-01 20:29 UTC, mdcfe requested changes

2020-07-01 20:29 UTC, md678685 commented on Essentials/src/messages.properties
> +itemloreNoLine=\u00a74Your selected item does not have lore text on line \u00a7c{0}\u00a74.
```suggestion
itemloreNoLine=\u00a74Your held item does not have lore text on line \u00a7c{0}\u00a74.
```

2020-07-01 20:29 UTC, md678685 commented on Essentials/src/plugin.yml
> +    aliases: [ilore, eilore, eitemlore]
```suggestion
    aliases: [lore, elore, ilore, eilore, eitemlore]
```

`/lore` seems like a reasonable alias - whereas `/name` for `/itemname` might be ambiguous, `/lore` seems to be more obviously related to items.

2020-07-02 03:34 UTC, pop4959 approved these changes

2020-07-06 18:46 UTC, mdcfe approved these changes

2020-07-06 18:46 UTC, merged