Add UserTeleportHomeEvent
EssentialsX/Essentials pull request #3403
Opened 2020-06-21 19:03 UTC by JRoy

Adds an event which allows developers to see & cancel when users attempt to teleport home. This event is needed over `UserTeleportEvent` due to the fact that it would be extremely difficult to accurately filter it by the /home command.

Closes #3401

2020-06-22 09:23 UTC, pop4959 requested changes

2020-06-22 09:23 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandhome.java
> +import org.bukkit.Bukkit;
We won't need this import

2020-06-22 09:23 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandhome.java
> +                    Bukkit.getServer().getPluginManager().callEvent(event);
The server is already in scope of this method

2020-06-22 09:23 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandhome.java
> +                    Bukkit.getServer().getPluginManager().callEvent(event);
=

2020-06-22 09:23 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandhome.java
> +        Bukkit.getServer().getPluginManager().callEvent(event);
We can get the server from the user

2020-06-22 09:23 UTC, pop4959 commented on Essentials/src/net/ess3/api/events/UserTeleportHomeEvent.java
> +    public UserTeleportHomeEvent(IUser user, Location target, HomeType homeType) {
It may be useful to have the home name relayed in the event as well

2020-06-22 09:23 UTC, pop4959 commented on Essentials/src/net/ess3/api/events/UserTeleportHomeEvent.java
> +        RESPAWN
Maybe `SPAWN` instead of `RESPAWN`, since the player is not really respawning, they are just teleporting to spawn (the location)

2020-06-22 19:05 UTC, pop4959 submitted a review, later dismissed

2020-06-24 18:43 UTC, JRoy commented
Merge conflicts resolved

2020-06-24 18:44 UTC, pop4959 approved these changes

2020-06-24 20:20 UTC, md678685 commented
I'd prefer adding a `Cause` enum to the new events added in #3192 (needs rebase) as this can be used to filter other types of teleports, like tpa/tpahere/home/warp etc.

2020-07-08 18:52 UTC, mdcfe approved these changes

2020-07-08 18:53 UTC, merged