Correctly handle explicitly denied permissions for users without a permissions plugin
EssentialsX/Essentials pull request #3419
Opened 2020-06-27 11:23 UTC by zml2008

to finally end the `/hat` saga, hopefully for good

2020-06-27 15:00 UTC, JRoy requested changes
Small nitpick, otherwise looks fine to me

2020-06-27 15:00 UTC, JRoy commented on Essentials/src/plugin.yml
> -    description: If the player has this permission, they will not have to sleep for the night to be skipped
Already pending in #3337, can be removed here

2020-06-29 03:03 UTC, pop4959 approved these changes

2020-06-29 03:43 UTC, darbyjack approved these changes

2020-07-02 02:05 UTC, JRoy approved these changes

2020-07-06 18:36 UTC, mdcfe approved these changes

2020-07-06 18:40 UTC, merged