Add config note regarding displayname
EssentialsX/Essentials pull request #3535
Opened 2020-07-24 23:54 UTC by JasonHorkles

Up to you if you think this is necessary, but it'll hopefully at least stop people from wondering why they have double prefixes/suffixes

2020-07-25 00:30 UTC, pop4959 commented
If I recall correctly username is only their actual username though (which would not include things such as their nickname). It would probably be better to leave `{DISPLAYNAME}` as is, and instead remove `{PREFIX}` and `{SUFFIX}` from the default if we were to consider this.

2020-07-25 00:37 UTC, JasonHorkles commented
Like that?

2020-08-04 14:59 UTC, mdcfe requested changes

2020-08-04 14:59 UTC, md678685 commented on Essentials/src/config.yml
> +  # Note: Using the {PREFIX} and {SUFFIX} placeholders along with {DISPLAYNAME} may cause double prefixes/suffixes to be shown in chat
This should probably mention under *what* scenario `{PREFIX}` and `{SUFFIX}` will result in duplication, namely when `add-prefix-suffix: true` is set.

2020-08-04 14:59 UTC, md678685 commented on Essentials/src/config.yml
> -  #format: '&7{PREFIX}&r {DISPLAYNAME}&r &7{SUFFIX}&r: {MESSAGE}'
If the message above is improved, there's no reason to remove this example.

2020-08-22 13:15 UTC, mdcfe approved these changes

2020-08-22 13:15 UTC, merged