remove deprecated UserMap#getUserFromBukkit usage
EssentialsX/Essentials pull request #3557
Opened 2020-07-31 22:38 UTC by uf0h

replace deprecated UserMap#getUserFromBukkit

Tested cases:
online player
offline player
offline player which has never joined

2020-08-01 00:02 UTC, pop4959 reviewed
Does this even need to be run asynchronously anymore? Would be good to look into, because the code in UserMap for the method you removed (as shown below) implies that this may be the only reason that it was. In that case, it would be good to simplify the code further.

https://github.com/EssentialsX/Essentials/blob/c86e1a5973445c72c31e68271acd554954b5d6b7/Essentials/src/com/earth2me/essentials/UserMap.java#L239

2020-08-01 23:31 UTC, uf0h commented
> 
> 
> Does this even need to be run asynchronously anymore? Would be good to look into, because the code in UserMap for the method you removed (as shown below) implies that this may be the only reason that it was. In that case, it would be good to simplify the code further.
> 
> https://github.com/EssentialsX/Essentials/blob/c86e1a5973445c72c31e68271acd554954b5d6b7/Essentials/src/com/earth2me/essentials/UserMap.java#L239

You're right, it doesn't. Fixed it up :) 4de450c

2020-08-04 09:18 UTC, pop4959 submitted a review, later dismissed

2020-08-21 16:40 UTC, pop4959 requested changes

2020-08-21 16:40 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/commands/Commandseen.java
> +            if (FormatUtil.validIP(args[0])) {
You removed a permission check here.

2021-01-02 03:33 UTC, JRoy commented
Closing due to staleness + probable side effects

2021-01-02 03:33 UTC, closed without merging