isPassable is not compatible with all versions
EssentialsX/Essentials pull request #3569
Opened 2020-08-04 10:53 UTC by pop4959

Fixes #3549.

Removed the isPassable check entirely, as it is not compatible with 1.12 and prior, nor does it seem to have any meaningful impact on the command to begin with (it was added to replace a getSafeDestination call which didn't make much sense to begin with).

2020-08-04 15:25 UTC, md678685 commented
As far as I can tell, the `isPassable` check is used to prevent embedding trees in walls/cliffs/etc, whereas `getSafeDestination` was previously used to just ensure trees would always spawn on a sensible surface. Removing this check means users are likely to spawn trees in the wrong place.

2020-08-04 15:34 UTC, JRoy requested changes
Not the correct fix, even if it was you also forgot the check in `Commandtree` :P. The correct way to solve this is to have a hardcoded material check for versions 1.8.8-1.12.2 of "passable" blocks and just use `isPassable` for 1.13 and higher.

2020-08-04 19:59 UTC, pop4959 commented
> Not the correct fix, even if it was you also forgot the check in `Commandtree` :P. The correct way to solve this is to have a hardcoded material check for versions 1.8.8-1.12.2 of "passable" blocks and just use `isPassable` for 1.13 and higher.

You're the person who wrote this code lol

2020-08-04 20:32 UTC, pop4959 commented
> As far as I can tell, the `isPassable` check is used to prevent embedding trees in walls/cliffs/etc, whereas `getSafeDestination` was previously used to just ensure trees would always spawn on a sensible surface. Removing this check means users are likely to spawn trees in the wrong place.

@md678685 I did not remove the check without testing; I've found that trees were not able to be spawned on/in "passable" locations such as grass, nor in walls. @JRoy can correct me if that's wrong, because he is the one who added it. We could most likely also simplify it to just make sure that the locations above the block where the tree is being placed is air. I'm not a fan of the idea of duplicating the entirety of the `isPassable` material list for legacy versions.

2020-08-04 20:46 UTC, JRoy commented
The behavior of spawnTree changes per version iirc; There's a reason this check was in place. You don't have to make a giant list tho, just put tall grass and air in it.

2020-08-04 20:57 UTC, pop4959 commented
@JRoy `LocationUtil#getTarget` doesn't target grass anyway since grass is a "transparent" material, so this boils down to just air in that case.

2020-08-05 19:55 UTC, pop4959 commented
This was changed as per MD's suggestion to use `isSolid` instead, which seems to work correctly on 1.8 and 1.16.

2020-08-12 00:07 UTC, JRoy approved these changes
ok ok ok ok oko ko kok ok okok ok ok oolk

2020-08-22 15:57 UTC, mdcfe approved these changes

2020-08-22 16:01 UTC, merged