Update links in readme
EssentialsX/Essentials pull request #3596
Opened 2020-08-14 22:08 UTC by Andre601

This PR updates several links:

- https://essentialsx.cf -> https://essentialsx.net
- Wiki links (Either github.io links or GitHub Wiki links) now point to their corresponding pages on the [actual wiki](https://essentialsx.net/wiki/Home.html)

Additionally did I also fix the readme mentioning `2.18.1` as the latest version while in reality it is `2.18.0`

2020-08-14 22:18 UTC, pop4959 submitted a review, later dismissed

2020-08-22 15:48 UTC, mdcfe requested changes

2020-08-22 15:48 UTC, mdcfe commented on README.md
> +Do you want to integrate with EssentialsX in your plugin? EssentialsX is available on the **ender.zone Maven repository** at https://ci.ender.zone/plugin/repository/everything/, and the EssentialsX a
```suggestion
Do you want to integrate with EssentialsX in your plugin? EssentialsX is available on the **ender.zone Maven repository** at https://ci.ender.zone/plugin/repository/everything/, and the EssentialsX artifact is `net.ess3:EssentialsX:2.18.1`.
```

2.18.1 is due to be released shortly (hopefully next couple of days), so this isn't really necessary.

2020-08-22 15:48 UTC, mdcfe approved these changes

2020-08-22 15:49 UTC, merged