Fixup some more bugs from command refactor
EssentialsX/Essentials pull request #3640
Opened 2020-08-30 16:07 UTC by JRoy

yeah

2020-09-02 07:01 UTC, md678685 requested changes

2020-09-02 07:01 UTC, mdcfe commented on Essentials/src/com/earth2me/essentials/Essentials.java
> +    public List<User> getOnlineUserList() {
Why do we need a variant that returns `List<User>` at all? This can just be inlined in `getOnlineUsers` as it was before.

2020-09-02 14:17 UTC, JRoy commented on Essentials/src/com/earth2me/essentials/Essentials.java
> +    public List<User> getOnlineUserList() {
👻ooOOoooOOOOoo you didn't see anything oooOOOOOOoooooOo 👻

2020-09-02 19:39 UTC, pop4959 commented on Essentials/src/com/earth2me/essentials/Essentials.java
> +    public List<User> getOnlineUserList() {
are you alright

2020-09-02 19:42 UTC, JRoy commented on Essentials/src/com/earth2me/essentials/Essentials.java
> +    public List<User> getOnlineUserList() {
no

2020-09-09 14:57 UTC, md678685 approved these changes

2020-09-09 14:58 UTC, md678685 commented
Rebased and merged as https://github.com/EssentialsX/Essentials/compare/4d2fbd04c58ae5c2b16ff34ea2308f011cdb7e8f...f89840545d025d6eb71fccd513b646fa6a3ce35f.

2020-09-09 14:58 UTC, closed without merging