Added support for registering enchantment names and aliases without reflection
EssentialsX/Essentials pull request #3669
Opened 2020-09-13 14:40 UTC by Auxilor

For registering enchantment/alias for tabcompletion through essentials as a dependency.
Changes this:
`((Map<String, Enchantment>) FieldUtils.readDeclaredStaticField(Enchantments.class, "ENCHANTMENTS", true)).put(name, enchantment);`
To this:
`Enchantments.registerEnchantment(name, enchantment)`

2020-09-16 05:04 UTC, pop4959 submitted a review, later dismissed

2020-10-05 08:49 UTC, md678685 requested changes

2020-10-05 08:49 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/Enchantments.java
> +            return;
```suggestion
        if (ENCHANTMENTS.containsKey(name) || ALIASENCHANTMENTS.containsKey(name)) {
            return;
        }
```

2020-10-05 08:49 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/Enchantments.java
> +            return;
```suggestion
        if (ENCHANTMENTS.containsKey(name) || ALIASENCHANTMENTS.containsKey(name) || !ENCHANTMENTS.containsValue(enchantment)) {
            return;
        }
```

2020-10-09 19:40 UTC, pop4959 approved these changes

2020-12-21 04:22 UTC, JRoy commented
Hello, can you please rebase this pull request so we can merge it! Thanks!

2020-12-21 16:24 UTC, mdcfe approved these changes

2021-01-02 04:11 UTC, merged