Update old EssentialsX URLs in issue templates
EssentialsX/Essentials pull request #3678
Opened 2020-09-19 20:34 UTC by Andre601

This updates the old https://essentialsx.github.io domains to the new https://essentialsx.net one.

2020-09-19 20:45 UTC, JRoy submitted a review, later dismissed

2020-09-19 21:09 UTC, pop4959 submitted a review, later dismissed

2020-10-05 08:37 UTC, md678685 requested changes

2020-10-05 08:37 UTC, md678685 commented on .github/ISSUE_TEMPLATE/request-a-feature.md
>        feature was recently added.
```suggestion
      also check the changelogs at https://github.com/EssentialsX/Essentials/releases
      to see if the feature was recently added.
```

The changelogs are more up-to-date than the wiki itself.

2020-10-05 13:20 UTC, md678685 approved these changes

2020-10-05 13:20 UTC, merged

2020-10-05 13:20 UTC, md678685 commented
Thanks for the PR!