Add support for material tags in enchant signs
EssentialsX/Essentials pull request #3694
Opened 2020-10-02 01:57 UTC by pop4959

Closes #3653

Tested with "swords" and works on Paper. Didn't have the opportunity to test on Spigot, but should be working.

2020-10-02 04:13 UTC, darbyjack submitted a review, later dismissed

2020-10-03 02:53 UTC, JRoy submitted a review, later dismissed

2020-11-26 04:54 UTC, JRoy submitted a review, later dismissed

2020-11-30 15:46 UTC, mdcfe requested changes

2020-11-30 15:46 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/signs/SignEnchant.java
> +            stack = itemName.equals("*") || itemName.equalsIgnoreCase("any") || tagProvider.tagExists(itemName) ? null : getItemStack(sign.getLine(1), 1, ess);
As it stands this will blow up on 1.12 and below. We should either make this null-safe or add a no-op provider implementation.

2021-01-27 18:50 UTC, JRoy approved these changes

2021-02-05 18:54 UTC, mdcfe approved these changes

2021-02-05 18:57 UTC, merged