Add more inventory commands
EssentialsX/Essentials pull request #3704
Opened 2020-10-03 19:16 UTC by JRoy

Closes #3195 and possibly others

2020-10-04 19:03 UTC, md678685 requested changes

2020-10-04 19:03 UTC, md678685 commented on Essentials/src/messages.properties
> +anvilCommandDescription=Opens up an Anvil.
```suggestion
anvilCommandDescription=Opens up an anvil.
```

2020-10-04 19:03 UTC, md678685 commented on Essentials/src/messages.properties
> +unsupportedBrand=\u00a74The platform you are running this on doesn't provide the capabilities for this feature
```suggestion
unsupportedBrand=\u00a74The server platform you are currently running does not provide the capabilities for this feature.
```

2020-10-04 19:03 UTC, md678685 commented on providers/BaseProviders/src/net/ess3/provider/ContainerProvider.java
> +    InventoryView openStonecutter(Player player);
```suggestion
    InventoryView openStonecutter(Player player);

```

2020-10-04 19:03 UTC, md678685 commented on providers/PaperProvider/src/net/ess3/provider/providers/PaperContainerProvider.java
> +    }
```suggestion
    }

```

2020-10-04 19:03 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/commands/Commandstonecutter.java
> +        ess.getContainerProvider().openStonecutter(user.getBase());
```suggestion

        ess.getContainerProvider().openStonecutter(user.getBase());
```

2020-10-04 19:03 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/commands/Commandsmithingtable.java
> +        ess.getContainerProvider().openSmithingTable(user.getBase());
```suggestion

        ess.getContainerProvider().openSmithingTable(user.getBase());
```

2020-10-04 19:03 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/commands/Commandloom.java
> +        ess.getContainerProvider().openLoom(user.getBase());
```suggestion

        ess.getContainerProvider().openLoom(user.getBase());
```

2020-10-04 19:03 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/commands/Commandgrindstone.java
> +        ess.getContainerProvider().openGrindstone(user.getBase());
```suggestion

        ess.getContainerProvider().openGrindstone(user.getBase());
```

2020-10-04 19:03 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/commands/Commandcartographytable.java
> +        ess.getContainerProvider().openCartographyTable(user.getBase());
```suggestion

        ess.getContainerProvider().openCartographyTable(user.getBase());
```

2020-10-04 19:03 UTC, md678685 commented on Essentials/src/com/earth2me/essentials/commands/Commandanvil.java
> +        ess.getContainerProvider().openAnvil(user.getBase());
```suggestion

        ess.getContainerProvider().openAnvil(user.getBase());
```

2020-10-05 09:05 UTC, md678685 requested changes

2020-10-05 09:05 UTC, md678685 commented on Essentials/src/plugin.yml
> +    aliases: [ecartographytable]
```suggestion
    aliases: [ecartographytable, carttable, ecarttable]
```

2020-10-05 09:05 UTC, md678685 commented on Essentials/src/plugin.yml
> +    aliases: [esmithingtable]
```suggestion
    aliases: [esmithingtable, smithtable, esmithtable]
```

2020-10-05 09:06 UTC, md678685 requested changes

2020-10-05 09:06 UTC, md678685 commented on providers/BaseProviders/src/net/ess3/provider/ContainerProvider.java
> +    InventoryView openStonecutter(Player player);
```suggestion
    InventoryView openAnvil(Player player);

    InventoryView openCartographyTable(Player player);

    InventoryView openGrindstone(Player player);

    InventoryView openLoom(Player player);

    InventoryView openSmithingTable(Player player);

    InventoryView openStonecutter(Player player);
```

2020-10-05 13:39 UTC, md678685 approved these changes

2020-10-05 13:45 UTC, merged

2020-10-05 23:12 UTC, ToonTown0909 commented
What are the command and permissions changes associated with this PR? This is so I may apply the updates to xeya.me.

2020-10-05 23:29 UTC, pop4959 commented
> What are the command and permissions changes associated with this PR? This is so I may apply the updates to xeya.me.

Should be the command name (as seen in `super()` in the code) prefixed with `essentials.`

So for example,
```java
    public Commandanvil() {
        super("anvil");
    }
```
should have a default permission of `essentials.anvil`. You can double check this if you want before submitting the permissions to Xeyame, but that should be correct.

2020-10-05 23:42 UTC, ToonTown0909 commented
Sounds good. I'll try my best to interpret and go from there, will let you know if I have any other questions. (Thank you!)

2020-10-08 17:01 UTC, ToonTown0909 commented
I do hereby confirm that the new commands and permissions in relation to this EssentialsX update have been merged into the xeya.me lists.