Remove acacia & birch tree type arguments from tree command
EssentialsX/Essentials pull request #3716
Opened 2020-10-08 17:18 UTC by montlikadani

`acacia` & `birch` literally **redundant** because in the for loop it finds if the argument is equal to these values. Also `TreeType` had already [BIRCH](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/TreeType.java?until=101dc61d0f76f4654ab3a72762aed7b1c7846843&autoSincePath=false#27) and [ACACIA](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/TreeType.java?until=101dc61d0f76f4654ab3a72762aed7b1c7846843&autoSincePath=false#59) values.

See https://github.com/EssentialsX/Essentials/blob/e2f17f11d3ec415ce7008cc34e4d163c7c4259ff/Essentials/src/com/earth2me/essentials/commands/Commandtree.java#L27-L32

_This PR does not produces any of fix, just cleanup_

2020-10-08 17:26 UTC, JRoy approved these changes, later dismissed

2020-10-08 19:36 UTC, pop4959 requested changes
Fix the unnecessary added whitespace, otherwise looks good.

2020-10-09 14:08 UTC, montlikadani commented
> 
> 
> Fix the unnecessary added whitespace, otherwise looks good.

Wouldn’t it be better with newline whitespaces so that the code doesn’t flow together?

2020-10-09 19:39 UTC, pop4959 commented
Nothing specific. Simply put, there were not spaces there before so there is no reason why you would need to add spaces for this change, except for the fact that it might be your preference. If you had changed the code where the spaces were added, it might be fine, but in this case your change is entirely within the if-else-clause and the formatting changes are outside of that. Just remove them please, there is no reason to argue over it.

2020-10-10 06:38 UTC, pop4959 approved these changes

2020-10-11 13:24 UTC, JRoy approved these changes

2020-10-12 14:09 UTC, JRoy commented
![](https://github.trello.services/images/mini-trello-icon.png) [Kit Serialization Support](https://trello.com/c/pejU4PDr/3-kit-serialization-support)

2020-10-12 14:09 UTC, JRoy commented
![](https://github.trello.services/images/mini-trello-icon.png) [Kit Serialization Support](https://trello.com/c/pejU4PDr/3-kit-serialization-support)

2020-10-13 07:47 UTC, merged