Prevent removal of cursed hat via direct hat (#3299)
EssentialsX/Essentials pull request #3758
Opened 2020-11-05 00:22 UTC by mxson

#3299 introduced a feature that would prevent players from swapping their hat using /hat, if their current hat had curse of binding on it. This was not extended to the direct hat feature, allowing players to still be able to swap their curse of binding hat by clicking on it with another hat. This resolves that issue.

2020-11-05 01:03 UTC, JRoy requested changes

2020-11-05 01:03 UTC, JRoy commented on Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
> +                    event.getWhoClicked().sendMessage(tl("hatCurse"));
Error messages for prevent type isn't sent here, so neither should this.

2020-11-05 01:03 UTC, JRoy commented on Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java
> +                if (VersionUtil.getServerBukkitVersion().isHigherThan(VersionUtil.v1_9_4_R01) && head != null && head.getEnchantments().containsKey(Enchantment.BINDING_CURSE) && !ess.getUser(event.ge
this check should be moved into the if statement above

2020-11-05 12:24 UTC, JRoy approved these changes
Looks good to me, just want reviews of others to make sure there's no backdoor in here

2020-11-05 13:15 UTC, mdcfe requested changes
I'd rather all the checks specific to curses are moved to a separate method, but the checks themselves look good.

2021-01-03 23:17 UTC, JRoy commented
Stale author, re-added in #3895

2021-01-03 23:17 UTC, closed without merging