Add option to disable players respawning at beds
EssentialsX/Essentials pull request #3802
Opened 2020-11-30 15:15 UTC by mdcfe

### Information

### Details

**Proposed feature**  
Add an option to toggle whether beds are considered valid respawn points in EssentialsX Spawn.

**Environments tested:**  
- [ ] [Latest](https://papermc.io/downloads) Paper Version (any OS, any Java 8+ version)
- [ ] CraftBukkit/Spigot/Paper 1.12.2 (any OS, any Java 8+ version)
- [ ] CraftBukkit 1.8.8 (any OS, any Java 8+ version)

2020-11-30 15:59 UTC, JRoy requested changes
Should only be caching config options ourselves if we mutate it in any way, which we don't here.

2020-11-30 15:59 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +    private boolean bedSpawnEnabled;
```suggestion
```

2020-11-30 15:59 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +        bedSpawnEnabled = _isBedSpawnEnabled();
```suggestion
```

2020-11-30 15:59 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +
```suggestion
    @Override
    public boolean isRespawnAtBed() {
        return config.getBoolean("respawn-at-home-bed", true);
    }
```

2020-11-30 16:01 UTC, mdcfe commented
> Should only be caching config options ourselves if we mutate it in any way, which we don't here.

@JRoy Not really, this is the standard for Essentials' configs and minimises touching config objects when not reloading.

2020-11-30 16:04 UTC, JRoy commented
@mdcfe The config object is already a cached representation of the config, this just creates a duplicated object in memory for no reason.
![we already do this a lot in Settings](https://user-images.githubusercontent.com/10731363/100633158-b6ccfe80-32fb-11eb-881e-3e6f4c066622.png)

i should also make a follow up pr for removing all these when not needed

2021-01-02 02:57 UTC, JRoy approved these changes

2021-01-02 03:02 UTC, merged