Add update checker
EssentialsX/Essentials pull request #3855
Opened 2020-12-22 06:00 UTC by JRoy

Adds an update checker to Essentials that will check for the latest version on startup, on player join (permission is `essentials.updatecheck`), or manually with `/ess version`

On startup, the update checker will fetch build information from a resource generated at compile time and determine if the build is a dev or stable build. If it's a stable build, the update checker will only check for a new release; while a dev build will check for any new commits.

There are 6 different types of messages the update checker will return;
* Identical: The current build is the latest stable release or latest dev build. This message is only shown in the `/ess version` command.
* Behind: If the current build is stable, it's an entire stable build behind, otherwise it's one or more dev builds behind.
* Diverged: The current build was made from a branch other than `2.x` and is also one or more dev builds behind the latest commit on `2.x`.
* Diverged Latest: The current build was made from a branch other than `2.x` but is based on the latest commit from `2.x`.
* Unknown: The current build either has invalid build information or was customly built. This message is show everywhere but on player join.
* Error: There was an error while fetching the latest version information.

2020-12-31 17:41 UTC, JRoy commented
TODO @mdcfe: Custom chart on bstats for branch name

2021-02-16 13:51 UTC, mdcfe requested changes

2021-02-16 13:51 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsUpdateChecker.java
> +    private final static String BRANCH = "2.x";
```suggestion
    private static final String REPO = "EssentialsX/Essentials";
    private static final String BRANCH = "2.x";
```
wh-

2021-02-16 13:51 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/Essentials.java
> +                "com.earth2me.essentials.commands.Command", "essentials.", null);
```suggestion
            "com.earth2me.essentials.commands.Command", "essentials.", null);
```
Unnecessary spacing change

2021-02-16 13:51 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/Essentials.java
> +                    Bukkit.getLogger().log(Level.INFO, "CommandBlock at {0},{1},{2} issued server command: /{3} {4}", new Object[]{bSenderBlock.getX(), bSenderBlock.getY(), bSenderBlock.getZ(), comma
```suggestion
                    Bukkit.getLogger().log(Level.INFO, "CommandBlock at {0},{1},{2} issued server command: /{3} {4}", new Object[] {bSenderBlock.getX(), bSenderBlock.getY(), bSenderBlock.getZ(), commandLabel, EssentialsCommand.getFinalArg(args, 0)});
```

2021-02-16 13:51 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/Essentials.java
> +                Bukkit.getLogger().log(Level.INFO, "{0} issued server command: /{1} {2}", new Object[]{cSender.getName(), commandLabel, EssentialsCommand.getFinalArg(args, 0)});
```suggestion
                Bukkit.getLogger().log(Level.INFO, "{0} issued server command: /{1} {2}", new Object[] {cSender.getName(), commandLabel, EssentialsCommand.getFinalArg(args, 0)});
```

2021-02-16 13:51 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
> +                    }
Maybe move this into a `showJoinUpdateCheck` method or something?

2021-02-16 13:51 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/metrics/MetricsWrapper.java
> +        addCustomChart(new Metrics.SimplePie("releaseBranch", EssentialsUpdateChecker::getVersionBranch));
Preferably put this in its own method for consistency

2021-02-16 13:51 UTC, mdcfe commented on build.gradle
>          inputs.property('fullVersion', fullVersion)
```suggestion
        // Always process resources if version string or git branch changes
        inputs.property('fullVersion', fullVersion)
```

2021-02-16 13:51 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandessentials.java
> +                        //TODO download link? (https://github.com/EssentialsX/Website/issues/26)
Pending adding a release page to the website

2021-03-06 15:23 UTC, mdcfe requested changes

2021-03-06 15:23 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsUpdateChecker.java
> +        }
```suggestion
        final InputStream inputStream = EssentialsUpdateChecker.class.getClassLoader().getResourceAsStream("release");
        if (inputStream != null) {
            final List<String> versionStr = new BufferedReader(new InputStreamReader(inputStream, StandardCharsets.UTF_8)).lines().collect(Collectors.toList());
            if (versionStr.size() == 2) {
                if (versionStr.get(0).matches("\\d+\\.\\d+\\.\\d+-dev\\+\\d\\d-[0-9a-f]{7,40}")) {
                    identifier = versionStr.get(0).split("-")[2];
                    dev = true;
                } else {
                    identifier = versionStr.get(0);
                }
                branch = versionStr.get(1);
            }
        }
```

Afaik `Objects.requireNonNull` in the static block here will cause the class to not initialize, so EssentialsX won't load if the release file is missing.

2021-03-06 15:23 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsUpdateChecker.java
> +    private EssentialsUpdateChecker() {
Should have a config option to disable - as it stands, this PR makes external connections without letting the user control them.

Probably worth making the methods in this class non-static, passing in `ISettings` here, and only triggering update checks if enabled in config.

2021-03-06 15:23 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsUpdateChecker.java
> +public final class EssentialsUpdateChecker {
Possibly move to `com.earth2me.essentials.updatecheck.UpdateChecker`? Base package is cluttered as it is.

2021-03-06 15:23 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsUpdateChecker.java
> +                pendingReleaseFuture = null;
Why set to null here?

2021-03-06 15:23 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsUpdateChecker.java
> +        }
```suggestion
        return pendingReleaseFuture;
        }
```
Without this, we would just return the cached result. On first run this is null and causes NPEs:

![error](https://i.imgur.com/mM43mqW.png)

2021-03-06 15:23 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsUpdateChecker.java
> +    public static String[] getVersionMethods(final boolean sendLatestMessage, final boolean verboseErrors) {
...methods? 
```suggestion
    public static String[] getVersionMessages(final boolean sendLatestMessage, final boolean verboseErrors) {
```

2021-03-06 15:23 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsUpdateChecker.java
> +    public static class UpdateToken {
```suggestion
    public static class Version {
```

2021-03-06 16:18 UTC, mdcfe submitted a review, later dismissed

2021-03-06 16:27 UTC, mdcfe approved these changes

2021-03-06 16:29 UTC, merged