Fix damage from exploding beds being cancelled.
EssentialsX/Essentials pull request #3874
Opened 2020-12-26 20:35 UTC by Nathat23

This PR fixes #3872 

Proposed fix: Add check if exploding block material is tnt.

Environments tested: git-Paper-325 (MC: 1.16.4)

2020-12-26 20:41 UTC, pop4959 commented
What happens with beds if tnt explosion damage is disabled? You should make sure that servers are still able to disable beds.

2020-12-26 20:52 UTC, Nathat23 commented
> What happens with beds if tnt explosion damage is disabled? You should make sure that servers are still able to disable beds.

If protect.prevent.tnt-playerdamage is enabled, then TNT doesn't do damage but beds still do.

2020-12-26 21:00 UTC, pop4959 commented
> If protect.prevent.tnt-playerdamage is enabled, then TNT doesn't do damage but beds still do.

Sorry if not clear, what I'm really asking is with this PR are servers able to both:
- enable tnt damage but disable bed damage
- enable bed damage but disable tnt damage

Just want to make sure because this was catching both before, but it should be possible to control them individually. In addition, you should check that any other exploding blocks are handled correctly too.

2020-12-26 21:05 UTC, Nathat23 commented
> > If protect.prevent.tnt-playerdamage is enabled, then TNT doesn't do damage but beds still do.
> 
> Sorry if not clear, what I'm really asking is with this PR are servers able to both:
> 
>     * enable tnt damage but disable bed damage
> 
>     * enable bed damage but disable tnt damage
> 
> 
> Just want to make sure because this was catching both before, but it should be possible to control them individually. In addition, you should check that any other exploding blocks are handled correctly too.

The PR just means that the config option for tnt damage only disables tnt damage and not bed damage. I can add config options for bed damage if required?

2020-12-26 21:29 UTC, pop4959 commented
Would only be required if the change breaks behavior that previously was expected.

2021-01-03 23:28 UTC, JRoy requested changes

2021-01-03 23:28 UTC, JRoy commented on EssentialsProtect/src/main/java/com/earth2me/essentials/protect/EssentialsProtectEntityListener.java
> +            final EntityDamageByBlockEvent edbEvent = (EntityDamageByBlockEvent) event;
dangerous cast, need to be checked

2021-01-04 09:32 UTC, Nathat23 commented on EssentialsProtect/src/main/java/com/earth2me/essentials/protect/EssentialsProtectEntityListener.java
> +            final EntityDamageByBlockEvent edbEvent = (EntityDamageByBlockEvent) event;
It's checked on line 64

2021-06-11 15:04 UTC, JRoy approved these changes

2021-06-11 15:06 UTC, merged