Add WarpModifyEvent
EssentialsX/Essentials pull request #3875
Opened 2020-12-27 01:50 UTC by DarkEyeDragon

Adds a cancellable event for when warps are modified (altered/removed/created).

Closes #3868

2021-01-02 02:34 UTC, JRoy requested changes

2021-01-02 02:34 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commanddelwarp.java
> +        Location location = ess.getWarps().getWarp(args[0]);
```suggestion
        final Location location = ess.getWarps().getWarp(args[0]);
```

2021-01-02 02:34 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commanddelwarp.java
> +            Bukkit.getServer().getPluginManager().callEvent(event);
```suggestion
            Bukkit.getServer().getPluginManager().callEvent(event);
            if (event.isCancelled()) {
                return;
            }
```

2021-01-02 02:34 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandsetwarp.java
> +            Bukkit.getServer().getPluginManager().callEvent(event);
```suggestion
            Bukkit.getServer().getPluginManager().callEvent(event);
            if (event.isCancelled()) {
                return;
            }
```

2021-01-02 02:34 UTC, JRoy commented on Essentials/src/main/java/net/essentialsx/api/v2/events/WarpModifyEvent.java
> +    private static final HandlerList handlers = new HandlerList();
```suggestion
    private static final HandlerList handlers = new HandlerList();
```

2021-01-02 02:34 UTC, JRoy commented on Essentials/src/main/java/net/essentialsx/api/v2/events/WarpModifyEvent.java
> +    }
```suggestion
```

2021-01-02 02:34 UTC, JRoy commented on Essentials/src/main/java/net/essentialsx/api/v2/events/WarpModifyEvent.java
> +    }
```suggestion
    }
    
    public HandlerList getHandlers() {
        return handlers;
    }

    public static HandlerList getHandlerList() {
        return handlers;
    }
```

2021-01-02 02:38 UTC, JRoy commented on Essentials/src/main/java/net/essentialsx/api/v2/events/WarpModifyEvent.java
> +
```suggestion

```

2021-01-02 02:48 UTC, JRoy approved these changes

2021-01-08 20:03 UTC, mdcfe approved these changes

2021-01-08 20:20 UTC, merged