Improve logging of dangerous userdata edge cases
EssentialsX/Essentials pull request #3969
Opened 2021-02-08 15:28 UTC by mdcfe

### Information

This PR does not close an existing issue. (todo: link relevant issues)

### Details

**Proposed feature:**  
This commit improves the logging of a few edge cases that can lead to loss of userdata:
- Third-party plugins forcing creation of a NPC account which could not be found on the usermap, even if the account file exists
- UserMap#trackUUID being called with a conflicting UUID but replace set to false

**Environments tested:**    

OS: Windows 10 20H2 (19042)

Java version: 11.0.7+10

- [x] Most recent Paper version (1.16.5, git-Paper-466)
- [ ] ~~CraftBukkit/Spigot/Paper 1.12.2~~
- [ ] ~~CraftBukkit 1.8.8~~

2021-02-08 15:34 UTC, JRoy requested changes
Exception stack traces are going to be useful in the process of debugging what plugins are causing this

2021-02-08 15:34 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/UserMap.java
> +                        ess.getLogger().info("Found UUID " + uuid.toString() + " for player " + name + ", but player already has a UUID (" + names.get(keyName).toString() + "). Not replacing UUID in
Exception

2021-02-08 15:34 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/api/Economy.java
> +        LOGGER.warning(MessageFormat.format(WARN_EXISTING_NPC_CREATE, name, user.getConfigUUID()));
Exception

2021-02-08 15:34 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/api/Economy.java
> +                    LOGGER.info(MessageFormat.format(WARN_PLAYER_UUID_NO_NAME, name, player.getUniqueId().toString()));
Exception

2021-02-08 15:49 UTC, JRoy approved these changes

2021-02-08 15:50 UTC, merged

2021-02-09 07:39 UTC, mibby commented
@JRoy Essentials blew up with exceptions when someone typed ``/baltop``. Using EssentialsX dev 1112 (2.19.0-dev+70-34fdcf8).

https://paste.gg/p/anonymous/c91d995181bb4b9b87b2f47009794dc0/files/40922ecedf7c43f2bd32cbb9f4439e8a/raw

2021-02-09 13:42 UTC, JRoy commented
@mibby can you open a bug report with that so we can properly track it. (Make sure you fill out the whole template) It is intended so we can find bugs with our UserMap