Make FormatUtil respect the &x color codes
EssentialsX/Essentials pull request #4095
Opened 2021-03-28 21:40 UTC by JRoy

Fixes #4094

2021-03-29 00:45 UTC, JRoy commented
after merge, new unformat methods should be used in #4048

2021-04-12 17:19 UTC, Proximyst requested changes

2021-04-12 17:19 UTC, Proximyst commented on Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java
> +                    sb.append(FormatUtil.unformatString(s).replaceAll(" ", "_"));
```suggestion
                    sb.append(FormatUtil.unformatString(s).replace(" ", "_"));
```

2021-04-12 17:19 UTC, Proximyst commented on Essentials/src/main/java/com/earth2me/essentials/items/AbstractItemDb.java
> +                sb.append("name:").append(FormatUtil.unformatString(meta.getDisplayName()).replaceAll(" ", "_")).append(" ");
```suggestion
                sb.append("name:").append(FormatUtil.unformatString(meta.getDisplayName()).replace(" ", "_")).append(" ");
```

2021-05-02 20:14 UTC, pop4959 approved these changes

2021-05-02 20:18 UTC, merged