Add config option to respawn jailed players to spawn
EssentialsX/Essentials pull request #4132
Opened 2021-05-01 18:40 UTC by JRoy

Adds `teleport-to-spawn-when-freed-from-jail` option to config to respawn the player after jailed.

Closes #4123

2021-05-10 16:14 UTC, mdcfe commented
Kinda tempted to replace this with a `teleport-when-freed: (spawn|back|off)` setting (and fall back to the existing back-when-freed option), especially since the new option in this PR depends on the other one anyway

2021-06-08 14:00 UTC, mdcfe requested changes

2021-06-08 14:00 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +        }
```suggestion
if (config.hasProperty("teleport-when-freed")) {
            // snakeyaml more like cursedyaml
            final String value = config.getString("teleport-when-freed", "back").replace("false", "off");
            try {
                return TeleportWhenFreePolicy.valueOf(value.toUpperCase(Locale.ROOT));
            } catch (IllegalArgumentException e) {
                throw new RuntimeException("Invalid value \"" + value + "\" for config option \"teleport-when-freed\"!", e);
            }
        }

        return TeleportWhenFreePolicy.BACK;
```

- `TeleportWhenFreePolicy.valueOf(config.getString("teleport-when-freed", "back"))` doesn't allow for non-uppercase values
- If `teleport-when-freed` exists but has an invalid value, we should error instead of defaulting
- Is it worth adding a `InvalidConfigValueException extends RuntimeException` for this? There's possible other cases where we should throw for invalid settings so the user knows what's wrong, instead of silently defaulting and leaving users wondering why settings aren't working

2021-06-08 20:58 UTC, pop4959 approved these changes
LGTM

2021-06-08 22:23 UTC, mdcfe approved these changes

2021-06-09 01:04 UTC, merged