Add prevent-type permissions for /itemname
EssentialsX/Essentials pull request #4133
Opened 2021-05-01 19:09 UTC by JRoy

Adds `essentials.itemname.prevent-type.<material_name>` permissions

Closes #4044

2021-05-02 19:18 UTC, pop4959 requested changes, later dismissed
Should use an allow-type permission instead of a prevent-type, otherwise we'll have the same mess as we do with hat permissions currently.

The issue is that implementing a negative permission like prevent-type will revoke access (which is a behavior change in Essentials) for servers that utilize wildcards. On the contrary, allow-type could just be set to false for specific materials, and servers using wildcards for this will still grant themselves access to all items by default.

2021-05-02 20:15 UTC, JRoy commented
> Should use an allow-type permission instead of a prevent-type, otherwise we'll have the same mess as we do with hat permissions currently.
> 
> The issue is that implementing a negative permission like prevent-type will revoke access (which is a behavior change in Essentials) for servers that utilize wildcards. On the contrary, allow-type could just be set to false for specific materials, and servers using wildcards for this will still grant themselves access to all items by default.

Fixed

2021-05-28 11:55 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commanditemname.java
> +        if (((wildcard != null && wildcard) && material == null) || ((wildcard != null && wildcard) && material) || ((wildcard == null || !wildcard) && (material != null && material))) {
```suggestion
        if (((wildcard != null && wildcard) && material == null) || ((wildcard != null && wildcard) && (material != null && material)) || ((wildcard == null || !wildcard) && (material != null && material))) {
```

Same logic as above

2021-05-28 11:55 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandhat.java
> +            if (((wildcard != null && wildcard) && material == null) || ((wildcard != null && wildcard) && material) || ((wildcard == null || !wildcard) && (material != null && material))) {
```suggestion
            if (((wildcard != null && wildcard) && material == null) || ((wildcard != null && wildcard) && (material != null && material)) || ((wildcard == null || !wildcard) && (material != null && material))) {
```

For future reference:

| Material \ Wildcard | unset | false | true  |
|---------------------|-------|-------|-------|
| unset               | allow | allow | deny  |
| false               | allow | allow | allow |
| true                | deny  | deny  | deny  |

2021-05-28 12:15 UTC, KennyTV commented
Would look JRoy times better if you had a tristate enum à la
```java
if (wildcard == Thing.TRUE && (material == Thing.UNSET || material == Thing.TRUE))
                || (material == Thing.TRUE && (wildcard == Thing.UNSET ||  wildcard == Thing.FALSE));
```
and you pulled the || on material and wilcard in each line into an extra var as well

2021-05-28 13:13 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/User.java
> +        // Graceful time before the first afk check call.
```suggestion
        // Graceful time before the first afk check call. 
```

2021-05-28 13:15 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commanditemname.java
> +            user.sendMessage(tl("itemnameInvalidItem"));
Maybe a no permission message here?

2021-05-28 17:32 UTC, mdcfe approved these changes

2021-05-28 17:35 UTC, merged