Random teleport improvements
EssentialsX/Essentials pull request #4271
Opened 2021-06-25 07:54 UTC by pop4959

Supersedes #3538.
Closes #1893, #3469, #3479.

Various improvements for Essentials' random teleportation feature.

Should be complete as-is, other than potential code clean-up and testing before merging.

Miscellaneous points of interest:
- #easteregg pre-cache configuration removed (it was hardly in use anyways, and doesn't make any difference after first tp + with multiple locations the number of locations to compute could get very expensive).
- EssentialsUpgrade to convert old single location random teleport and retain prior behavior.
- Random respawn with `random-respawn` and `random-respawn-location` configuration options.
- Random teleport signs by adding `randomteleport` to the `enabledSigns` list in the config, writing `[RandomTeleport]` in the first line on the sign, and optionally the name of the location on the second line.
- Configuration option for default location (where to teleport when typing /tpr with no arguments) that defaults to the current world.
- Configuration option for per location permissions (`essentials.tpr.location.<name>`), functioning similarly to how per warp permissions work.
- `/settpr` now requires the location name as an argument to set center/ranges for.
- Can teleport other players with the `essentials.tpr.others` and the command `/tpr <name> <player>`.
- Console can now execute `/tpr` with the name and player both as required arguments.
- Fixed an issue where on older versions of the game the default center location would be a block too high.
- Fixed an issue where events modifying random teleportation parameters would cause incorrect caching.
- Fixed the issue of random locations below y=0 being considered invalid (world height can be lower now in 1.17).

2021-12-04 03:28 UTC, JRoy commented
@pop4959 can you resolve conflicts for this whenever you have time

2021-12-11 20:36 UTC, pop4959 commented
Updated, would like to see a few more people test this before merging though. Grab a build from [actions](https://github.com/EssentialsX/Essentials/actions/runs/1567843927) if you want to try it, and just be sure to backup tpr.yml so you can easily switch back to regular Essentials builds.

2021-12-12 14:07 UTC, Leahcimkrob commented
You can enter a value after it for tpr, but you can always get by in the farmworld.

2021-12-12 19:34 UTC, pop4959 commented
> You can enter a value after it for tpr, but you can always get by in the farmworld.

Not quite sure what you mean here, can you elaborate?

2021-12-12 21:27 UTC, Leahcimkrob commented
https://github.com/EssentialsX/Essentials/discussions/4679
I posted that in the discussions. So I got your invitation to test your build. With the / tpr I still got into the farming world, even if I had specified a value such as Nether.

2021-12-12 21:28 UTC, pop4959 commented
> #4679 I posted that in the discussions. So I got your invitation to test your build. With the / tpr I still got into the farming world, even if I had specified a value such as Nether.

Can you provide a list of the worlds you have on your server and your tpr.yml file

2021-12-13 19:42 UTC, Leahcimkrob commented
Ok i got it.

After a few teleoports with / tpr, I suddenly landed in the Void in the Nether. Can that still be fixed?

2021-12-25 21:27 UTC, Envel-Nikita-Gutsenkov submitted a review, later dismissed

2022-02-13 20:56 UTC, Envel-Nikita-Gutsenkov submitted a review, later dismissed

2022-05-17 12:15 UTC, Chris6ix commented
Hey, just wondering if there are any updates on this?
Just wanted to open a new issue, but saw that the Feature I want was already suggested (and apparently also been worked on) (#3469)
Would be awesome having this :)

2022-05-17 20:25 UTC, pop4959 commented
@Chris6ix Updated the build for you :)

This work is for the most part done, probably just a few minor changes here and there, but otherwise just needs to be tested thoroughly before the 2.20 milestone.

2022-05-18 12:34 UTC, Chris6ix commented
Alright I downloaded it, and I'm going to test it when I got some spare time (Have Exams rn :/ )
Thanks for updating the build :)

Is there anything specific that needs to be tested or something?
I can imagine that the basics have already been tested?

Btw, is there an approximate release date for 2.20?

2022-05-18 19:04 UTC, pop4959 commented
> Alright I downloaded it, and I'm going to test it when I got some spare time (Have Exams rn :/ ) Thanks for updating the build :)
> 
> Is there anything specific that needs to be tested or something? I can imagine that the basics have already been tested?
> 
> Btw, is there an approximate release date for 2.20?

No problem. Nothing specific, just making sure multi-world teleports, /tpr, /settpr commands, configuration, etc all appear and behave as expected and are intuitive to use, not buggy, etc. The basics have been tested so ideally try it out on a server and see if you find any issues using it.

2022-05-18 22:08 UTC, Chris6ix commented
> No problem. Nothing specific, just making sure multi-world teleports, /tpr, /settpr commands, configuration, etc all appear and behave as expected and are intuitive to use, not buggy, etc. The basics have been tested so ideally try it out on a server and see if you find any issues using it.
> 
> There isn't an ETA For 2.20 currently but you can track progress in the [milestone](https://github.com/EssentialsX/Essentials/milestone/14) here on Github.

Okay thank you!
I will test these things when i got some spare time and get back to you with the results ;)

2022-05-28 22:26 UTC, Chris6ix commented
Hey @pop4959 i found some free time and tested the multi world rtp feature :)
I loaded the 4 worlds from my Server to a completely fresh paper `1.18.2 #350` Test Server with only EssX `2.20.0-dev+6-2448e2a` (your build) and Multiverse-Core `4.3.2-SNAPSHOT-b870`
I also generated a completely new EssX folder and left everything to default.

I teleported myself to each of the world's spawns using `mvtp <WorldName>` and then just did `/settpr <WorldName> center`
This worked perfectly for all the worlds.

I then teleported myself to each world and made about 20 random teleports in each world, each time checking with [Xaeros World Map](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map) that the teleports were really random and that it was not picking a location more than once or something.
Everything worked perfectly fine besides the rtps in the nether...there were 2 issues:
Out of the 20 times, I got teleported 2 times into a wall
Out of the 20 times, I got teleported 3 times on top of the nether roof

So I think the nether part needs to be adjusted a bit with a max height just under the nether roof for example and a fix for the teleporting into walls. The rest looks fine to me :)

Thanks again for working on this great feature!
If you need any more testing or something, just ping me here.

Cheers

2022-05-28 23:01 UTC, pop4959 commented
@Chris6ix Hey, thanks for doing such a thorough test! Glad to hear everything's working for you. 😄 

Not sure about the teleporting into walls/roof, I don't believe any changes have been made with regards to that. It should be using Essentials safe teleport feature (as all other teleport commands do), so unless you've turned that off random teleports should behave correctly.

I sometimes forget to keep this branch up-to-date, but feel free to continue testing it. Just ping me if you need any changes merged in from the current mainstream dev builds.

2022-05-28 23:17 UTC, Chris6ix commented
Hey @pop4959 thanks for the quick reply!
As I explained in my message from before, I generated a completely new EssX folder (so also a fresh config) and didn't even open it (the only file I checked was `tpr.yml` to check if all the worlds show up correctly). 
So all settings were on default, which for the teleport safety seems to be this:
![image](https://user-images.githubusercontent.com/65610536/170845572-50dd8f32-328d-438f-8d1e-79895972eb08.png)
So the teleport safety was enabled...and it still teleported me into walls / on top of the nether roof...
Or is that because I was in creative? (Because of explanation of `force-safe-teleport-location`)
If that is so, shouldn't the default be `true` to also prevent creative mode players from getting teleported into walls?

2022-05-28 23:19 UTC, pop4959 commented
Yes it is probably because you were in creative. The teleport is "safe" in creative mode since you do not take damage. Teleportation safety primarily concerns whether or not the player takes damage teleporting to the location.

You can test in survival or try setting that option to true if that is your preference.

2022-05-28 23:30 UTC, Chris6ix commented
Mhm okay I have `force-safe-teleport-location` now set to `true` and I'm not getting teleported into walls anymore in creative, but it still teleports me on top of the nether roof (Probably because its "safe" because you don't take damage...)
Is there something you can do to not make the nether roof count as "safe" / Or add a max tp height just for the nether dimension just under the nether roof, which seems to be `Y:121` ?

2022-05-28 23:37 UTC, pop4959 commented
Okay, that's something we can look into then. The intent is definitely not to teleport on top of the roof. Probably either the location being selected too high, or teleportation safety choosing a spot above the roof (although I believe it's already supposed to do this).

2022-05-31 13:52 UTC, goweiwen commented
Want to update that I've been using this PR on my server for more than a few months and it has been working great.

2022-07-05 14:16 UTC, JRoy requested changes
few things otherwise good!

2022-07-05 14:16 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsUpgrade.java
> +        ess.getRandomTeleport().updateConfig();
A couple problems with this upgrade;
* This should only be ran once (by checking/setting the `doneFile` with a unique upgrade key)
* The logic for this upgrade should be contained in the `EssentialsUpgrade` class and ideally not call any method in `RandomTeleport` as to not create an accidental regression down the road.

2022-07-05 14:16 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandsettpr.java
> +        randomTeleport.reloadConfig();
This invokes an I/O operation. Is there a reason why it's ran let alone before any arguments are even validated?

2022-07-05 14:16 UTC, JRoy commented on Essentials/src/main/java/net/ess3/api/events/UserRandomTeleportEvent.java
>      public UserRandomTeleportEvent(final IUser user, final Location center, final double minRange, final double maxRange) {
Event constructors aren't API, you can remove this if you're not using it

2022-08-14 08:37 UTC, pop4959 commented
TODO
- jroys comments above
- pre-validate random locations in chunks
- refactor / clean up some code

2024-11-24 23:07 UTC, JRoy approved these changes

2024-11-24 23:07 UTC, merged

2024-11-24 23:10 UTC, JRoy commented
This has beat the adventure pr for longest time from open to merge...

2024-11-24 23:42 UTC, PetyXbron commented
🚀🚀🚀

2024-12-14 02:39 UTC, DavidDoesCode commented
Im trying this out and have the follow config: (I tried many commands)

I'm finding that when I random tp - one of the coordinates are ALWAYS 1000 or -1000, which the other one is "random" 

It's spawning me on the "border" 

`default-location: '{mcverse_vanilla}'
excluded-biomes:
- cold_ocean
- deep_cold_ocean
- deep_frozen_ocean
- deep_lukewarm_ocean
- deep_ocean
- deep_warm_ocean
- frozen_ocean
- frozen_river
- lukewarm_ocean
- ocean
- river
- warm_ocean
locations:
  mcverse_vanilla:
    center:
      world: a58ce000-9699-4d7b-b91f-4644ce8955dc
      world-name: mcverse_vanilla
      x: 0.5
      y: 72.0
      z: 0.5
      yaw: -142.0070343017578
      pitch: 14.700003623962402
    min-range: 100.0
    max-range: 1000.0
  '{mcverse_vanilla}':
    center:
      world: bbfcef01-71a8-4676-8119-4cdad005180d
      world-name: world
      x: 0.0
      y: 63.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0
    min-range: -1000.0
    max-range: 1000.0
`

2024-12-14 02:41 UTC, Evidentsinger14 commented
PR comments are not for support. if you need help with something, please use the support channels in [MOSS](https://discord.gg/h8CnPSw)

2024-12-14 02:42 UTC, pop4959 commented
@DavidDoesCode You should not have a negative range in your config. That is not supported.

2024-12-14 05:20 UTC, DavidDoesCode commented
Maybe some better comments describing what the values should be.

But anyways, I'm pretty sure that the random respawn is not respecting beds:
`respawn-at-home-bed: true`

(I did try minrange with 0 but /essentials reload did not seem to work, restarting the server did)

2024-12-14 05:33 UTC, pop4959 commented
@DavidDoesCode If the commands allow you to enter a negative radius, please open a bug report. Same goes for any other issues or concerns you have.

If you have any other questions please use the support channels in MOSS as Evident has mentioned.