Add UserTeleportSpawnEvent
EssentialsX/Essentials pull request #4328
Opened 2021-07-06 21:55 UTC by Ansandr

### Details ###
I propose to add an event for listening to the player's teleportation to the spawn, and include it in the new api v2

I've recently had a case myself where having this event would have been a lot easier than having to listen to the `PlayerCommandPreprocessEvent`.

**Proposed feature:**  
Event is called when the user teleports to the spawn using command

**Environments tested:**    

OS: Windows 10 x64

Java version: 16 x64

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

2021-07-06 22:16 UTC, JRoy requested changes
Few small grammer things, also would be nice for there to be a getController method to get the person who caused the teleport (so if someone did `/spawn PlayerName`), or null if there is none.

2021-07-06 22:16 UTC, JRoy commented on EssentialsSpawn/src/main/java/net/essentialsx/api/v2/events/UserTeleportSpawnEvent.java
> + * Called when a user is teleported home via the /spawn command.
```suggestion
 * Called before a user is teleported to spawn via the /spawn command.
```

2021-07-06 22:16 UTC, JRoy commented on EssentialsSpawn/src/main/java/net/essentialsx/api/v2/events/UserTeleportSpawnEvent.java
> +     */
```suggestion
    /**
     * @return The user who is being teleported to spawn.
     */
```

2021-07-06 22:16 UTC, JRoy commented on EssentialsSpawn/src/main/java/net/essentialsx/api/v2/events/UserTeleportSpawnEvent.java
> +     * @return Teleportation destination location.
```suggestion
     * The spawn location of the {@link #getUser() user's} {@link #getSpawnGroup() group}.
     * @return The spawn location of the user's group.
```

2021-07-06 22:16 UTC, JRoy commented on EssentialsSpawn/src/main/java/net/essentialsx/api/v2/events/UserTeleportSpawnEvent.java
> +     * @return Name of group
```suggestion
     * The {@link #getUser() user's} group used to determine their spawn location.
     * @return The user's group.
```

2021-07-07 12:15 UTC, Ansandr commented
> 
> 
> Few small grammer things, also would be nice for there to be a getController method to get the person who caused the teleport (so if someone did `/spawn PlayerName`), or null if there is none.

Done

2021-07-07 18:46 UTC, JRoy approved these changes

2021-07-07 18:52 UTC, merged

2025-05-07 07:31 UTC, DereC4 commented
UserTeleportSpawnEvent