Add the ability for tab complete to use display names instead of player names
EssentialsX/Essentials pull request #4432
Opened 2021-08-02 22:01 UTC by cyberkitsune

### Information

This PR closes #4431. 

### Details

**Proposed feature:**  
This feature adds a new configuration option, `change-tab-complete-name`

When `change-tab-complete-name` is turned on, `getPlayers()` in `EssentialsCommand` will use `getDisplayName()` instead of `getName()`; Populating the list with display names instead of player names.

**Environments tested:**    

OS: Linux, Pterodactyl Java 11 Docker Container

Java version:  openjdk version "11.0.10" 2021-01-19

- [X] Most recent Paper version (1.17.1, git-Paper-151)
- [X] CraftBukkit/Spigot/Paper 1.12.2
- [X] CraftBukkit 1.8.8

**Demonstration:**  
![image](https://user-images.githubusercontent.com/920550/127929360-03ffc600-9dd0-4b0a-a9ee-183d0a09989d.png)

2021-08-02 22:37 UTC, JRoy requested changes
A few things plus you should return `Collections.emptyList()` in the following places:

https://github.com/EssentialsX/Essentials/blob/b84207f95510ee6cf0fcc47138771cabe93a1f31/Essentials/src/main/java/com/earth2me/essentials/commands/Commandmsg.java#L63

https://github.com/EssentialsX/Essentials/blob/b84207f95510ee6cf0fcc47138771cabe93a1f31/Essentials/src/main/java/com/earth2me/essentials/commands/Commandmail.java#L298

2021-08-02 22:37 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/EssentialsCommand.java
> +                players.add(ess.getSettings().changeTabCompleteName() ? ChatColor.stripColor(user.getDisplayName()) : user.getName());
Please use `FormatUtil#stripFormat`

2021-08-02 22:37 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/EssentialsCommand.java
> +                players.add(ess.getSettings().changeTabCompleteName() ? ChatColor.stripColor(user.getDisplayName()) : user.getName());
Please use `FormatUtil#stripFormat`

2021-08-02 22:58 UTC, JRoy submitted a review, later dismissed

2021-08-19 19:47 UTC, mdcfe commented on Essentials/src/main/resources/config.yml
> +# This option will cause Essentials to display a player's displayname instead of username when tab completing Essentials commands.
```suggestion
# This option will cause Essentials to show players' displaynames instead of usernames when tab completing Essentials commands.
```

2021-08-19 19:56 UTC, mdcfe submitted a review, later dismissed

2021-08-19 19:59 UTC, mdcfe approved these changes

2021-08-19 20:00 UTC, merged