Add playtime command
EssentialsX/Essentials pull request #4562
Opened 2021-10-05 20:13 UTC by MisterMelDev

### Information

This PR closes #3827. 

### Details

**Proposed feature:**  

Allow players to view their own or another player's playtime.

**Environments tested:**    

OS: Windows 10

Java version: ``java version "16.0.1" 2021-04-20``

- [x] Most recent Paper version (1.17.1, git-Paper-fdd5c65)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**  

![2021-10-05_22 11 40](https://user-images.githubusercontent.com/18401198/136095685-7d00e789-c611-4186-bf18-0a04c62636fd.png)
![2021-10-05_22 11 47](https://user-images.githubusercontent.com/18401198/136095691-4b4ae5f6-6d68-44b6-ba51-93468c4018be.png)

2021-10-05 20:58 UTC, JRoy requested changes

2021-10-05 20:58 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandplaytime.java
> +    // For some reason, in 1.13 PLAY_ONE_MINUTE = ticks played = what used to be PLAY_ONE_TICK
```suggestion
    // For some reason, in 1.13 PLAY_ONE_MINUTE = ticks played = what used to be PLAY_ONE_TICK
```

2021-10-05 20:58 UTC, JRoy commented on Essentials/src/main/resources/messages_en.properties
> +playtime=§6{0}§6''s Playtime\:§r {1}
Do not add messages to this file, add them to `messages.properties`, not `messages_en.properties`.
```suggestion
```

2021-10-05 20:58 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandplaytime.java
> +        if (args.length == 1) {
```suggestion
        if (args.length == 1 && sender.isAuthorized("essentials.playtime.others", ess)) {
```

2021-10-05 20:58 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandplaytime.java
> +        }
```suggestion
        if (args.length > 0) {
            target = getPlayer(server, sender, args, 0, false, false);
        } else if (sender.isPlayer()) {
            target = sender.getUser(ess);
        } else {
            throw new NotEnoughArgumentsException();
        }
```

2021-10-05 21:14 UTC, JRoy requested changes

2021-10-05 21:14 UTC, JRoy commented on Essentials/src/main/resources/messages.properties
> +playtime=\u00a76{0}\u00a76''s Playtime\:\u00a7r {1}
please add these in alphabetical order

2021-10-05 21:14 UTC, JRoy commented on Essentials/src/main/resources/messages_en.properties
> +xmppNotConfigured=XMPP is not configured properly. If you do not know what XMPP is, you may wish to remove the EssentialsXXMPP plugin from your server.
```suggestion
xmppNotConfigured=XMPP is not configured properly. If you do not know what XMPP is, you may wish to remove the EssentialsXXMPP plugin from your server.

```

2021-10-06 00:38 UTC, JRoy requested changes

2021-10-06 00:38 UTC, JRoy commented on Essentials/src/main/resources/messages.properties
> +playtimeCommandUsage=/<command> [player]
```suggestion
playtimeCommandUsage=/<command> [player]
playtimeCommandUsage1=/<command>
playtimeCommandUsage1Description=Shows your time played in game
playtimeCommandUsage2=/<command> <player>
playtimeCommandUsage2Description=Shows the specified player''s time played in game
```

2021-10-06 00:38 UTC, JRoy commented on Essentials/src/main/resources/messages.properties
> +playtimeCommandDescription=Shows a player''s playtime
```suggestion
playtimeCommandDescription=Shows a player''s time played in game
```

2021-10-06 00:38 UTC, JRoy commented on Essentials/src/main/resources/plugin.yml
> +    description: Shows a player's playtime
```suggestion
    description: Shows a player's time played in game
```

2021-10-06 00:38 UTC, JRoy commented on Essentials/src/main/resources/messages.properties
> +playtime=\u00a76{0}\u00a76''s Playtime\:\u00a7r {1}
```suggestion
playtime=\u00a76Playtime\:\u00a7c {0}
playtimeOther=\u00a76Playtime of {1}\u00a76\:\u00a7c {0}
```

2021-10-06 00:38 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandplaytime.java
> +        sender.sendMessage(tl("playtime", target.getDisplayName(), DateUtil.formatDateDiff(playtimeMs)));
```suggestion
        final IUser target;
        final String key;
        
        if (args.length > 0 && sender.isAuthorized("essentials.playtime.others", ess)) {
            target = getPlayer(server, sender, args, 0);
            key = "playtimeOther";
        } else if (sender.isPlayer()) {
            target = sender.getUser(ess);
            key = "playtime";
        } else {
            throw new NotEnoughArgumentsException();
        }

        final long playtimeMs = System.currentTimeMillis() - (target.getBase().getStatistic(PLAY_ONE_TICK) * 50);
        sender.sendMessage(tl("playtime", target.getDisplayName(), DateUtil.formatDateDiff(playtimeMs)));
```

2021-10-06 00:39 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandplaytime.java
> +        sender.sendMessage(tl("playtime", target.getDisplayName(), DateUtil.formatDateDiff(playtimeMs)));
```suggestion
        sender.sendMessage(tl(key, target.getDisplayName(), DateUtil.formatDateDiff(playtimeMs)));
```

2021-10-06 00:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandplaytime.java
> +        sender.sendMessage(tl(key, target.getDisplayName(), DateUtil.formatDateDiff(playtimeMs)));
```suggestion
        sender.sendMessage(tl(key, DateUtil.formatDateDiff(playtimeMs), target.getDisplayName()));
```

2021-10-06 00:48 UTC, JRoy approved these changes

2021-10-23 19:29 UTC, merged

2021-11-04 12:54 UTC, Catches commented
@MisterMelDev, would it be possible to add offline playtime support? This would be insanely useful.

2021-11-07 13:06 UTC, MisterMelDev commented
> @MisterMelDev, would it be possible to add offline playtime support? This would be insanely useful.

The way I implemented this, it currently wouldn't be possible. I'm using the built-in Bukkit statistics system, which also contains a statistic for playtime, but this can only be retrieved when the player is online. The plugin would have to store the playtime in the player data or something. I'm a bit busy currently, but maybe someone else could make a PR for that?

2023-03-26 01:03 UTC, F8ER commented
> The way I implemented this

Greetings! Just in case if still interested in offline data, there are a few implementation like the following wonderful one for a reference:
- <https://www.spigotmc.org/resources/playtime.26016>;
- <https://github.com/Twi5TeD/PlayTime>.