Rewrite User storage and UUID cache
EssentialsX/Essentials pull request #4581
Opened 2021-10-17 14:14 UTC by JRoy

A rewrite of user loading, user caching, uuid caching, and user memory management.

Closes #4512
Closes #4342
Closes #4566
Closes #4581

---

### Technical Breakdown of `ModernUserMap` + `ModernUUIDCache`

TODO :trollface: 

---

Checklist;
- [x] Store username history more sanely
- [x] Rewrite the UUID cache
- [x] Rewrite the UserMap and replace the old UserMap
- [x] Add ABI backwards compatibility for certain hot methods in old UserMap

2021-10-27 16:53 UTC, tadhgboyle commented
:shipit:

2021-10-28 22:21 UTC, pop4959 submitted a review, later dismissed
//noinspection ConstantConditions

2021-11-04 15:42 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUUIDCache.java
> +     * * In a UUID->Name based map, multiple uuids now point to the same map
```suggestion
     * In a UUID->Name based map, multiple uuids now point to the same map
```

2021-12-04 14:43 UTC, mdcfe commented
Bumping to 2.20 as per internal discussions

2021-12-09 12:17 UTC, Gilthunderx commented
PULLL!

2021-12-15 02:44 UTC, darbyjack commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUUIDCache.java
> +     * This map is baked by a file-based cache. If this cache is missing, a new
backed*?

2021-12-16 01:09 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUUIDCache.java
> +     * This map is baked by a file-based cache. If this cache is missing, a new
```suggestion
     * This map is backed by a file-based cache. If this cache is missing, a new
```

2022-02-13 08:54 UTC, pop4959 submitted a review, later dismissed

2022-08-24 19:37 UTC, mdcfe requested changes
Side note: do we want an API interface for `ModernUserMap`? Just so there's an explicit (and limited) set of methods that plugins should expect to use, otherwise I anticipate people will just call internal methods

2022-08-24 19:37 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
> +            kfuser.update(event.getPlayer());
hmmmm

2022-08-24 19:37 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/api/Economy.java
> +            user = getUserByUUID(UUID.nameUUIDFromBytes(("NPC:" + (ess.getSettings().isSafeUsermap() ? StringUtil.safeString(name) : name)).getBytes(Charsets.UTF_8)));
This is likely to break plugin accounts (eg Towny) on servers that previously disabled username sanitisation?

2022-08-24 19:37 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/economy/vault/VaultEconomyProvider.java
> +        return com.earth2me.essentials.api.Economy.playerExists(UUID.nameUUIDFromBytes(("NPC:" + (ess.getSettings().isSafeUsermap() ? StringUtil.safeString(playerName) : playerName)).getBytes(Charset
Same as before, potential to break migrating servers with `use-safe-usermap: false`?

2022-08-24 19:37 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUUIDCache.java
> +    }
Do these need to be public? ~~(and how much of this class needs to be public?)~~

2022-08-24 19:37 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUserMap.java
> +        uuidCache.updateCache(user.getUUID(), user.getName());
Do we definitely always want to update the UUID cache here?

2022-08-24 19:37 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUserMap.java
> +            uuidCache.updateCache(uuid, player.getName());
```suggestion
            // This is a real player, cache their UUID
            uuidCache.updateCache(uuid, player.getName());
```

2022-08-24 19:37 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUserMap.java
> +                .build(this);
Not sure about this - do we actually want `load` exposed publicly?

2022-08-24 19:37 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUserMap.java
> +            ess.getLogger().log(Level.INFO, "Essentials updated the underlying Player object for " + user.getUUID());
In theory would break online users if some other plugin gives us their own `Player` type for an online player for some reason. Not sure if there's any cases where we would want to guard against this?

2022-08-24 19:37 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandessentials.java
> +                    final File backupFolder = new File(ess.getDataFolder(), "userdata-npc-backup-boogaloo");
Include the date/time in the folder name? Would make it easier for admins to identify if they did it multiple times

2022-08-25 21:14 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
> +            kfuser.update(event.getPlayer());
i'm not touching these calls, it broke when i removed them and worked when i added them

2022-08-25 21:15 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUUIDCache.java
> +    }
They're used in EssentialsUpgrade

2022-08-25 21:40 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUserMap.java
> +                .build(this);
not a big deal buddy

2022-08-25 21:40 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUserMap.java
> +        uuidCache.updateCache(user.getUUID(), user.getName());
yeah thanks for asking

2022-08-25 21:40 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/userstorage/ModernUserMap.java
> +            ess.getLogger().log(Level.INFO, "Essentials updated the underlying Player object for " + user.getUUID());
why would they do that

2022-08-31 14:15 UTC, mdcfe commented on .idea/checkstyle-idea.xml
> +        <ConfigurationLocation id="9c559e66-f9d0-4553-b942-bd6095fd8a13" type="PROJECT_RELATIVE" scope="All" description="EssentialsX">
Don't need to commit this

2022-09-04 14:42 UTC, mdcfe approved these changes

2022-09-04 14:42 UTC, merged

2022-09-17 13:45 UTC, mibby commented
@JRoy Not entirely sure where to leave feedback for this but noticed that every time Citizens loads an npc (server restarts, teleporting around), Essentials spams creating a user for them.
https://paste.gg/p/anonymous/e7fd399e9db6436d8ed3c5ee15dae70a/files/febeaa22bd6846a8aa7d8a93acb63b85/raw

EssentialsX-2.20.0-dev+5
https://ci.ender.zone/view/All/job/EssentialsX-Experimental/100007/
Citizens2 dev 2705
https://ci.citizensnpcs.co/job/Citizens2/

2022-09-18 17:23 UTC, Boothin commented
> @JRoy Not entirely sure where to leave feedback for this but noticed that every time Citizens loads an npc (server restarts, teleporting around), Essentials spams creating a user for them. https://paste.gg/p/anonymous/e7fd399e9db6436d8ed3c5ee15dae70a/files/febeaa22bd6846a8aa7d8a93acb63b85/raw
> 
> EssentialsX-2.20.0-dev+5 https://ci.ender.zone/view/All/job/EssentialsX-Experimental/100007/ Citizens2 dev 2705 https://ci.citizensnpcs.co/job/Citizens2/

I had this issue and found it was caused by jail.yml having old data that was formatted in a different way than new jails. Since I don't actually use the jails, removing the file contents worked for me.