Fix tpaccept world teleport permissions
EssentialsX/Essentials pull request #4732
Opened 2022-01-02 23:36 UTC by mind04

### Details
Fix a world teleport permission bypass. A user with permission for a word is able to provide access to that world to users without permission. 

**Environments tested:**    

OS: Debian 10

Java version:  17

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:** 
user1 has permission to world X
user2 has no permission to world X

With use of tpahere:
user1 goes to world X and executes /tpahere
user2 executes /tpaccept -> tp of user2 to world X

With use of tpa:
Both users are in the same world.
user2 executes /tpa user1
user1 teleports to word X
user1 executes /tpaccept -> tp of user2 to world X

2023-04-09 21:06 UTC, JRoy approved these changes, later dismissed

2023-04-09 21:06 UTC, JRoy commented
would like @mdcfe's or @pop4959's thoughts

2023-04-09 21:35 UTC, pop4959 submitted a review, later dismissed
LGTM. Line 90 seems to be a regression from #3801, and the second permission check on line 94 was added in that same PR, which should follow logically that the condition is backwards currently there as well.

2023-04-09 21:36 UTC, pop4959 commented
AKA JRoy what were you thinking :)

2023-04-09 22:16 UTC, JRoy commented
@mind04 Please update the pull request with 2.x or allow maintainer edits from pull requests.

2023-04-10 21:40 UTC, mind04 commented
Done

2023-04-10 21:41 UTC, pop4959 approved these changes

2023-04-10 21:44 UTC, mdcfe requested changes
Thanks for spotting this!

However, I feel these conditions should be pulled out into local variables. The reason this slipped through in the first place is because these giant chained conditions are impossible to read at a glance. It would be nice to make the logic here a bit more readable.

Will follow up this review with suggested changes in a moment.

2023-05-24 14:56 UTC, mind04 commented
> Will follow up this review with suggested changes in a moment.

Any progress?

Is it an option to merge the pull as is? It is fixing a real issue, does not increase complicity and does not prevent a clean-up at a later date.

2023-05-24 15:22 UTC, mdcfe commented
Hey, we did discuss this internally but apparently I forgot to respond here - apologies for that.

I did work on refactoring the class somewhat, the results of which can be seen here: https://github.com/EssentialsX/Essentials/commit/ff7569c77daa37664b15b64f70b3744898a465d3

I don't think we came to a decision internally at the time, but I would be happy to merge with the above changes, pending @pop4959 or @JRoy double checking it.

2024-01-03 12:01 UTC, closed without merging

2024-01-03 19:23 UTC, pop4959 commented
@mind04 Apologies for taking so long to get back to you on this PR. It looks like it's been automatically closed due to the repository being deleted. Just want to let you know in case this wasn't intentional.