Add per-command command cooldown bypass permissions
EssentialsX/Essentials pull request #4759
Opened 2022-01-16 17:33 UTC by JRoy

Adds the permission `essentials.commandcooldowns.bypass.<command name>` to bypass the cooldown for a specific command.

Closes #4747

2022-02-13 07:51 UTC, pop4959 requested changes, later dismissed
nitpick but otherwise looks good

2022-02-13 07:51 UTC, pop4959 commented on Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java
> +                } else if (entry.getKey().matcher(fullCommand).matches() ) {
```suggestion
                } else if (entry.getKey().matcher(fullCommand).matches()) {
```

2022-06-16 00:22 UTC, matipoirierg reviewed
Been testing this for months, working fine without issues.

2023-02-13 23:13 UTC, mdcfe approved these changes

2023-02-13 23:19 UTC, merged