Added /sell multipliers with configuration
EssentialsX/Essentials pull request #4770
Opened 2022-01-20 17:52 UTC by justinmtech

### Information

This PR closes #3934

### Details

**Proposed feature:**  

Sell multipliers! The idea is for servers to be able to control how much players can /sell their items for based on configurable permissions. I re-wrote this based on @Chew's feedback to work more similarly to the multiple set-home system so that it doesn't have to iterate over all of a players' permissions and instead, check if they have the ones in the config.
https://github.com/EssentialsX/Essentials/issues/3934

**Environments tested:**    

OS: Windows 10

Java version:  OpenJDK 17.0.1

- [x] Most recent Paper version (1.18.1, #153)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**  

Screenshot: [https://i.imgur.com/ju0jMUy.png](url)
Here I give myself a diamond and sell it with no permissions (as op), then I give myself the "essentials.sell.multiplier.double" permission and as you can see, my sell price is double.
Plugin Download: https://www.dropbox.com/s/56y3zf6ibarlwj4/EssentialsX-2.19.3-dev%2B6-739600e-sell-multipliers-redo.jar?dl=0

2023-09-03 00:14 UTC, JRoy requested changes
also needs to account for sell sign

2023-09-03 00:14 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/ISettings.java
> +    BigDecimal getMultiplier(final User user);
```suggestion

    BigDecimal getMultiplier(final User user);
```

2023-09-03 00:14 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandsell.java
> +        final BigDecimal worth = ess.getWorth().getPrice(ess, is) == null ? null : ess.getWorth().getPrice(ess, is).multiply(ess.getSettings().getMultiplier(user));
```suggestion
        final BigDecimal originalWorth = ess.getWorth().getPrice(ess, is);
        final BigDecimal worth = originalWorth == null ? null : originalWorth.multiply(ess.getSettings().getMultiplier(user));
```

2023-09-03 00:14 UTC, JRoy commented on Essentials/src/main/resources/config.yml
> +# If a player has more than one multiplier permission, it will pick the highest one.
```suggestion
# Allow players to receive multipliers for items sold with /sell or the sell sign.
# You can set the default multiplier using the 'default' rank below.
# To grant different multipliers to different people, you need to define a 'multiplier-rank' below.
# Create the 'multiplier-rank' below, and give the matching permission: essentials.sell.multiplier.<multiplier-rank>
```

2024-04-08 19:09 UTC, zzkanezz2 commented
Can we please get sell multipliers implemented to latest essentialsex?

2024-12-09 01:05 UTC, JRoy approved these changes

2024-12-09 01:08 UTC, merged