Added max lore feature request #4772
EssentialsX/Essentials pull request #4773
Opened 2022-01-21 17:23 UTC by justinmtech

### Information

This PR closes #4772

### Details

**Proposed feature:**  

Configure the max lines of lore that can be added with /itemlore add.
Adds config setting "max-item-lore" and an error message when a user tries to add a new line of lore to an item with the max.
https://github.com/EssentialsX/Essentials/discussions/4772

**Environments tested:**    

OS: Windows 10

Java version:  OpenJDK 17.0.1

- [x] Most recent Paper version (1.18.1, #153)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**  

Screenshot: [https://imgur.com/a/dQ6TedQ](url)
Plugin Download: [https://www.dropbox.com/s/jpl35j9rr57bs8m/EssentialsX-2.19.3-dev%2B10-b220c22-max-lore-feature-4772.jar?dl=0](url)

2022-01-23 00:53 UTC, JRoy requested changes
Few things plus please add a `essentials.itemlore.bypass` permission to bypass this limit

2022-01-23 00:53 UTC, JRoy commented on Essentials/src/main/resources/config.yml
> +max-item-lore: 10
```suggestion
# Set the maximum amount of lore lines a user can set with the /itemlore command.
# Users with the essentials.itemlore.bypass permission will be able to bypass this limit.
max-itemlore-lines: 10
```

2022-01-23 00:53 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +        return config.getInt("max-item-lore", 10);
```suggestion
        return config.getInt("max-itemlore-lines", 10);
```

2022-01-23 00:53 UTC, JRoy commented on Essentials/src/main/resources/messages.properties
> +itemloreMaxLore=\u00a74You cannot add more lore to this item.
```suggestion
itemloreMaxLore=\u00a74You cannot add any more lore lines to this item.
```

2022-01-23 01:07 UTC, justinmtech commented
Thanks! Looks good to me.

2022-03-19 16:01 UTC, mdcfe commented
Hey @justinmtech, any updates on these changes?

2023-08-08 18:45 UTC, JRoy approved these changes

2023-08-08 18:46 UTC, merged