Add ability to register custom item transformers.
EssentialsX/Essentials pull request #4871
Opened 2022-03-24 19:19 UTC by Golfing7

### Information

This PR closes Nothing.

### Details

**Proposed feature:**  
A system to allow plugin developers to add custom item transformers to metadata on items. Would be useful for plugins seeking to add custom item templates that could be dynamic or have special data on the item.

**Environments tested:**    

OS: Windows 10

Java version: 1.8.0_281

- [ ] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ x ] CraftBukkit 1.8.8

**Demonstration:**  

A demonstration isn't fully applicable to the situation as it's not something that immediately affects anything.

2022-03-24 19:27 UTC, mdcfe commented
Thanks for your interest in contributing to EssentialsX!

As it stands, `MetaItemStack` has been long in need of a major overhaul which I've been working on in a private branch. Part of this rework would overlap with the functionality added in this PR, so I will need some time to consider whether it would make sense to merge this PR at this stage.

2023-12-31 18:30 UTC, Golfing7 commented
It's been a while, just would like to see if this could still be merged as the rework to `MetaItemStack` appears to have not come yet. Thanks!

2025-11-05 14:13 UTC, Golfing7 commented
Heyo! I recently found a need for this again and wanted to know if this could get merged in quickly. Thanks!

2025-11-16 03:56 UTC, JRoy requested changes
minor nit + fix the formatting issues + fix the merge conflicts

2025-11-16 03:56 UTC, JRoy commented on .checkstyle/checkstyle.xml
> -
undo this?

2025-11-17 17:27 UTC, Golfing7 commented on .checkstyle/checkstyle.xml
> -
Change reverted, this was a mistake.

2025-11-17 17:28 UTC, Golfing7 commented
I've addressed the changes. Should I modify anything else?

2025-11-17 17:45 UTC, JRoy requested changes
just some final codestyle nits

2025-11-17 17:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/utils/StringUtil.java
> +    private static final Pattern INVALIDCHARS = Pattern.compile("[^\t\n\r -~\u0085\u00A0-\uD7FF\uE000-\uFFFC]");
undo this too pls

2025-11-17 17:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/items/transform/PluginItemTransformer.java
> +            throw new IllegalArgumentException("Plugin cannot be null!");
```suggestion
        if (thePlugin == null) {
            throw new IllegalArgumentException("Plugin cannot be null!");
        }
```

2025-11-17 17:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/items/transform/PluginItemTransformer.java
> +    public PluginItemTransformer(Plugin thePlugin){
```suggestion
    public PluginItemTransformer(final Plugin thePlugin) {
```

2025-11-17 17:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java
> +    }
```suggestion
    private void transformItem(final String key, final String data){
        final PluginItemTransformer transformer = itemTransformers.get(key);

        //Ignore, the plugin is disabled.
        if (!transformer.getPlugin().isEnabled()) {
            return;
        }

        try {
            stack = transformer.apply(data, stack);
        } catch(final Throwable thr) {
            Bukkit.getLogger().severe(String.format("[Essentials] - Error applying data \"%s\" to itemstack! Plugin: %s, Key: %s", data, transformer.getPlugin().getName(), key));
            thr.printStackTrace();
        }
    }
```

2025-11-17 17:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java
> +    public static void unregisterItemTransformer(String key){
```suggestion
    public static void unregisterItemTransformer(final String key) {
```

2025-11-17 17:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java
> +        if(itemTransformers.containsKey(key)){
```suggestion
    public static void registerItemTransformer(final String key, final PluginItemTransformer itemTransformer) {
        //Warn people if they're trying to register over top of someone else.
        if (itemTransformers.containsKey(key)) {
```

2025-11-17 17:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java
> +    //Contains plugin registered item meta data transformers.
```suggestion
```

2025-11-17 18:01 UTC, Golfing7 commented
Addressed!

2025-11-18 13:33 UTC, Golfing7 commented
I flattened the commits and updated my usage of the logger.

2025-11-29 16:12 UTC, mdcfe approved these changes

2025-11-29 16:12 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/items/transform/PluginItemTransformer.java
> +    public PluginItemTransformer(final Plugin thePlugin) {
It could be neat to provide plugins with a way to create a transformer using a lambda, but I wouldn't say this is required for this PR.

2025-11-29 17:01 UTC, JRoy approved these changes

2025-11-29 17:44 UTC, merged