Update to 1.19
EssentialsX/Essentials pull request #4932
Opened 2022-06-07 19:40 UTC by JRoy

- [x] Mobs
- [x] API/VersionUtil/README
- [ ] items.json

thanks for your concern @broccolai

2022-06-07 19:48 UTC, JRoy commented
WHOEVER MERGES THIS PLEASE USE REBASE AND MERGE

2022-06-15 10:27 UTC, sando1234 requested changes
I found nothing wrong :D.

2022-06-15 14:36 UTC, mdcfe requested changes

2022-06-15 14:36 UTC, mdcfe commented on README.md
> +  1.16.5, 1.17.1, 1.18.2, 1.19.**
and

2022-06-15 15:06 UTC, codebycam commented on README.md
> +  1.16.5, 1.17.1, 1.18.2, 1.19.**
LGTM

2022-06-15 15:06 UTC, mdcfe approved these changes

2022-06-15 15:18 UTC, merged