Added permission node for Nickname Prefix bypass
EssentialsX/Essentials pull request #4995
Opened 2022-07-15 09:16 UTC by Zelathis

### Information

This PR closes #4994. 

### Details

**Proposed feature:**  

Allow a permission to determine whether the nickname prefix gets applied to a group or user. It also removes a statement that is not true in the essentials config, the nickname prefix is NOT included in the nickname max length.

**Environments tested:**    

OS: Windows 11

Java version:  17.0.2

- [x] Most recent Paper version (1.19, git-Paper-61)
- [x] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**  

Before change: https://i.imgur.com/HZaKazT.png
After change: https://i.imgur.com/QyitAPl.png

2022-07-15 09:21 UTC, Zelathis commented
I just noticed that I did not commit the plugin.yml, this will need the permission added for default op (if necessary)

2022-10-15 00:16 UTC, pop4959 approved these changes, later dismissed

2022-10-15 00:17 UTC, mdcfe requested changes
Thanks for the PR! I think `essentials.nick.prefix.hide` is a bit clearer of a name for the permission. Otherwise, I like this feature and would be happy to merge it if you're happy with changing the permission name.

2022-10-15 00:30 UTC, Evidentsinger14 commented
> Thanks for the PR! I think `essentials.nick.prefix.hide` is a bit clearer of a name for the permission. Otherwise, I like this feature and would be happy to merge it if you're happy with changing the permission name.

I feel like `essentials.nick.hideprefix` would be better - there aren’t any other permissions that have follow .nick.prefix (that I’m aware of).

2022-10-21 22:26 UTC, Baylem reviewed
I have updated the permission node with Evident's suggestion

2022-10-21 22:29 UTC, mdcfe commented on Essentials/src/main/resources/config.yml
> +# Users with essentials.nick.prefix.bypass will not be prefixed with the character(s)
```suggestion
# Users with essentials.nick.hideprefix will not be prefixed with the character(s)
```

2022-10-21 22:47 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/User.java
> +            nickname = isAuthorized("essentials.nick.hideprefix") ? nick : FormatUtil.replaceFormat(ess.getSettings().getNicknamePrefix()) + nick;
```suggestion
            if (isAuthorized("essentials.nick.hideprefix")) {
                nickname = nick;
            } else {
                nickname = FormatUtil.replaceFormat(ess.getSettings().getNicknamePrefix()) + nick;
            }
```

2022-10-25 06:43 UTC, mdcfe approved these changes

2022-10-25 06:44 UTC, merged