Improve PlayerTarget code
EssentialsX/Essentials pull request #5131
Opened 2022-10-11 02:46 UTC by JRoy

Don't know a good title but man that existing code is dumb.

Also resolves https://github.com/EssentialsX/Essentials/discussions/5114

2022-10-11 06:21 UTC, mdcfe commented
What does this even achieve?

2022-10-11 08:13 UTC, pop4959 commented
Yeah this seems like a regression, this change implies a higher likelihood of stale player references floating around, and also exposes an implementation detail.

The only thing I would potentially agree with is changing this to use a UUID instead of a name, but even that is extremely minor since the target is unlikely to remain relevant beyond a single user session.

2022-10-11 15:19 UTC, JRoy commented
made it uuids

2022-10-13 15:17 UTC, pop4959 requested changes

2022-10-13 15:17 UTC, pop4959 commented on Essentials/src/main/java/com/earth2me/essentials/PlayerTarget.java
> +        return uuid;
Implementation detail
```suggestion
```

2022-10-13 15:28 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/PlayerTarget.java
> +    private final UUID uuid;
```suggestion
    public final UUID uuid;
```

2022-10-13 15:38 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/PlayerTarget.java
> +    }
```suggestion
```

2022-10-15 00:24 UTC, pop4959 requested changes

2022-10-15 00:24 UTC, pop4959 commented on Essentials/src/main/java/com/earth2me/essentials/PlayerTarget.java
> +    public final UUID uuid;
This is an implementation detail
```suggestion
    private final UUID uuid;
```

2022-10-15 00:36 UTC, pop4959 approved these changes
lgtm

2022-10-15 00:41 UTC, merged