Nickname regex configurable
EssentialsX/Essentials pull request #5200
Opened 2022-12-28 19:26 UTC by Angelillo15

### Information

### Details

**Proposed feature:**  

Make /nick regex editable

**Environments tested:**    

OS: Windows 11 22H2

Java version: 11.0.6

- [x] Most recent Paper version (1.19.3, git-Paper-365)
- [x] CraftBukkit/Spigot/Paper 1.12.2
- [x] CraftBukkit 1.8.8

**Demonstration:**  

Before you can put a name for example with a "." and the only solution was to give the permission: essentials.nick.allowunsafe

![](https://i.imgur.com/DB4gsag.png)

![](https://i.imgur.com/GBmFSpB.png)

Now you can edit it in the config:

![](https://i.imgur.com/Phvxi44.png)

![](https://i.imgur.com/1FBrSr0.png)

![](https://i.imgur.com/FmD3i6B.png)

2023-04-19 14:43 UTC, YanisBft approved these changes
Useful addition, but in my opinion the config should be clearer. Like it could be named `allowed-nicks-regex` for instance.

2023-08-26 17:52 UTC, SrBedrock commented
Very necessary for servers that accept Bedrock players with Geyser

2025-03-24 16:41 UTC, JRoy requested changes

2025-03-24 16:41 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +        return config.getString("nick-regex", "^[a-zA-Z_0-9§]+$");
```suggestion
        return config.getString("allowed-nicks-regex", "^[a-zA-Z_0-9§]+$");
```

2025-03-24 16:41 UTC, JRoy commented on Essentials/src/main/resources/config.yml
> +nick-regex: '^[a-zA-Z_0-9§]+$'
```suggestion
# The regex pattern used to determine if a requested nickname should be allowed for use.
# If the a request nickname does not matched this pattern, the nickname will be rejected.
# Users with essentials.nick.allowunsafe will be able to bypass this check.
allowed-nicks-regex: '^[a-zA-Z_0-9§]+$'
```

2025-03-24 16:41 UTC, JRoy approved these changes

2025-03-24 16:43 UTC, merged