Fix teleport permission bypass exploit
EssentialsX/Essentials pull request #5238
Opened 2023-01-30 01:54 UTC by TauCubed

**Information**
This PR fixes https://github.com/EssentialsX/Essentials/issues/5237

**Details**
Players can bypass the "tpaccept" permission check when teleport delay is enabled. This can be done by an exploiter getting the target to /tpa to them, then, the exploiter starts a teleport timer to a location where they do not have "tpaccept" and then typing /tpaccept before that timer finishes. This will cause the first timer to teleport the exploiter to the location where they do not have "tpaccept" and then the timer for the target player will finish, resulting in the target teleporting to the exploiters location.

Proposed fix:
Check if the target is a player, if so, check if the player has permission to accept teleports.

Environments tested:
OS: Windows 10

Java version: OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)

- [X] Most recent Paper version (MC: 1.19.3)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

2023-04-30 17:18 UTC, pop4959 requested changes
Not really a huge fan of this implementation - could be much cleaner with a different approach.

For example, teleport requests could be cancelled if the a pending request exists when the target player changes worlds, or something like that.

2023-04-30 17:18 UTC, pop4959 commented on Essentials/src/main/java/com/earth2me/essentials/AsyncTimedTeleport.java
> +                            if (targetPlayer == null) return;
this check comes too late, `getPlayer` could already return null, uuid should always be non null

2023-04-30 17:18 UTC, pop4959 commented on Essentials/src/main/java/com/earth2me/essentials/AsyncTimedTeleport.java
> +                                if (!ess.getPermissionsHandler().hasPermission(targetPlayer, "essentials.tpaccept")) {
Is there a reason why you are using the permission handler instead of simply `targetPlayer#hasPermission`?

2023-04-30 17:18 UTC, pop4959 commented on Essentials/src/main/java/com/earth2me/essentials/AsyncTimedTeleport.java
> +                            } catch (Exception ex) {
is this happening a lot? don't feel like we should be getting exceptions on permission lookups for an online player

2024-11-25 03:15 UTC, JRoy commented
Closing due to inactivity

2024-11-25 03:15 UTC, closed without merging