add `hand` argument to `/recipe` to get recipe of item in main hand.
EssentialsX/Essentials pull request #5346
Opened 2023-05-12 01:01 UTC by Evidentsinger14

### Information

This PR closes #5259 

### Details

**Proposed feature:**  

**Environments tested:**    

OS: Windows 10

Java version:  Java 17

- [x ] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**  

![image](https://github.com/EssentialsX/Essentials/assets/46200123/e3a3544d-4626-45c2-897f-b49b480e248a)
![image](https://github.com/EssentialsX/Essentials/assets/46200123/425c3851-9b73-4bc4-92a6-b0aaadda158f)
![image](https://github.com/EssentialsX/Essentials/assets/46200123/67bd4f27-1517-4c0c-ae3a-5e24897cbc91)

2023-05-27 00:51 UTC, pop4959 requested changes

2023-05-27 00:51 UTC, pop4959 commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandrecipe.java
> +                throw new Exception(tl("recipeConsoleNoHands"));
Is there a more generic message that could be used here? For example `This command cannot be run by console`.

2023-05-27 00:51 UTC, pop4959 commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandrecipe.java
> +                throw new Exception(tl("recipeCannotBeAir"));
`recipeNone` already exists, this shouldn't need a more specific message

2023-05-27 00:51 UTC, pop4959 commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandrecipe.java
> +                throw new Exception(tl("recipeCannotBeAir"));
Actually, if you leave it as air I'm pretty sure it would just end up hitting the condition below anyway, so this check might not even be necessary

2023-05-27 01:58 UTC, pop4959 requested changes

2023-05-27 01:58 UTC, pop4959 commented on Essentials/src/main/resources/messages.properties
> +recipeCannotBeAir=No recipes exist for air.
```suggestion
```

2023-05-27 02:01 UTC, pop4959 submitted a review, later dismissed

2023-05-27 02:02 UTC, JRoy requested changes

2023-05-27 02:02 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandrecipe.java
> +        }
```suggestion
        if (args[0].equalsIgnoreCase("hand")) {
            if (!sender.isPlayer()) {
                throw new Exception(tl("consoleCannotUseCommand"));
            }
            final User user = sender.getUser(ess);
            
            itemType = user.getItemInHand();
        } else {
            itemType = ess.getItemDb().get(args[0]);
        }
```

2023-05-27 02:07 UTC, JRoy reviewed
lgtm

2023-05-27 02:07 UTC, JRoy approved these changes, later dismissed

2023-05-27 02:12 UTC, pop4959 submitted a review, later dismissed
double approval

2023-05-28 18:24 UTC, JRoy approved these changes

2023-05-28 18:27 UTC, merged