Add shortened values to economy system
EssentialsX/Essentials pull request #5369
Opened 2023-05-27 21:33 UTC by seppe-vandenberk

### Information

This PR closes #5352. 

### Details

**Proposed feature:**  

Adding shortened values for the /pay command like 115m instead of 115000000, all values upto Q (Quaddrillion are covered). Also /bal and /baltop show shortened numbers when the option is true in the config.yml. 

**Environments tested:**    

OS: Microsoft Windows 11

Java version: java version "18.0.2" 2022-07-19  

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**  

![image](https://github.com/EssentialsX/Essentials/assets/125284904/706ac078-b5c8-41dd-bfa5-d9455deb3138)
![image](https://github.com/EssentialsX/Essentials/assets/125284904/18ec907d-2687-4cf8-8a85-c03cb5567a13)

2023-06-01 04:51 UTC, Atticuss26 commented
I would like this

2023-06-12 14:32 UTC, powercasgamer requested changes

2023-06-12 14:32 UTC, powercasgamer commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +        return config.getBoolean("shortened-economy-numbers",true);
```suggestion
        return config.getBoolean("shortened-economy-numbers", true);
```

2023-06-12 14:32 UTC, powercasgamer commented on .idea/checkstyle-idea.xml
Shouldn't be deleted

2023-06-12 14:32 UTC, powercasgamer commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandpay.java
> +        if(ess.getSettings().isShortNumbersAllowed()){
```suggestion
        if (ess.getSettings().isShortNumbersAllowed()) {
```

2023-06-12 14:32 UTC, powercasgamer commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandpay.java
> +        } else{
```suggestion
        } else {
```

2023-06-12 14:32 UTC, powercasgamer commented on Essentials/src/main/java/com/earth2me/essentials/utils/NumberUtil.java
> +        if(ess.getSettings().isShortNumbersAllowed()) {
```suggestion
        if (ess.getSettings().isShortNumbersAllowed()) {
```

2023-06-12 14:32 UTC, powercasgamer commented on Essentials/src/main/java/com/earth2me/essentials/utils/NumberUtil.java
> +
```suggestion
```

2023-06-12 14:32 UTC, powercasgamer commented on Essentials/src/main/java/com/earth2me/essentials/utils/NumberUtil.java
> +        if(ess.getSettings().isShortNumbersAllowed()) {
```suggestion
        if (ess.getSettings().isShortNumbersAllowed()) {
```

2023-08-21 22:30 UTC, Evidentsinger14 commented
closing in favor of #5457

2023-08-21 22:30 UTC, closed without merging