Update to 1.20
EssentialsX/Essentials pull request #5389
Opened 2023-06-09 01:17 UTC by JRoy

just waiting on new aliases cc @mdcfe

2023-06-09 01:24 UTC, Aberdeener approved these changes

2023-06-09 01:55 UTC, LaxWasHere approved these changes

2023-06-11 11:42 UTC, joaoespanhol commented
i need update 1.20

2023-06-11 12:33 UTC, tanzbr reviewed
good

2023-06-11 14:41 UTC, iContinux approved these changes

2023-06-11 17:42 UTC, NekrosBurek approved these changes

2023-06-14 23:09 UTC, torchsmith approved these changes

2023-06-16 13:07 UTC, littlekan233 commented
support versions doesn't have 1.20, only 1.20.1

2023-06-16 21:29 UTC, JRoy commented
> support versions doesn't have 1.20, only 1.20.1

that's correct, we only support the latest patch version of an mc release

2023-06-17 12:29 UTC, dandud100 commented
So if this gets merged the 2.20.1 release will be build or am i misunderstanding this?

2023-06-17 12:38 UTC, Evidentsinger14 commented
When this is merged, a dev build for 2.20.1 will be published, yes.

2023-06-26 12:19 UTC, littlekan233 requested changes
add 1.20 support plz qwq

2023-06-26 16:32 UTC, torchsmith commented
Hi @mdcfe do you have any estimate on when you'll be able to get done the items.json task?

2023-06-27 11:08 UTC, kju196 commented
Please merge this early.

2023-07-01 17:47 UTC, pop4959 approved these changes, later dismissed

2023-07-01 18:55 UTC, mdcfe submitted a review, later dismissed

2023-07-01 18:55 UTC, mdcfe commented on Essentials/src/main/resources/items.json
> -  "dragonegg": "dragon_egg",
aaaaaaaa

2023-07-01 18:55 UTC, mdcfe commented on Essentials/src/main/resources/items.json
> +  "withersegg": "wither_spawn_egg",
aaaaaaaaaaaa

2023-07-01 19:05 UTC, mdcfe commented on EssentialsDiscordLink/src/main/java/net/essentialsx/discordlink/AccountLinkManager.java
> +        return isLinked(member.getId()) && removeAccount(member, DiscordLinkStatusChangeEvent.Cause.UNSYNC_API);
Uh

2023-07-01 19:20 UTC, mdcfe approved these changes

2023-07-01 19:37 UTC, merged