Add requirements for balancetop listing
EssentialsX/Essentials pull request #5394
Opened 2023-06-16 03:16 UTC by ayush03dev

### Information

This PR closes #5307 

### Details

**Proposed feature:**  

This pull request adds two requirements that the player must meet in order for their name to appear in the balance top list. Those two requirements are: **1) Minimum Balance** and **2) Minimum Playtime**

The requirements can be configured from the following additions to config.yml file:

```
# Requirements which must be met by the player to get their name shown in the balance top list.
# Playtime is in seconds.
baltop-requirements:
  minimum-balance: 0
  minimum-playtime: 0
```

**Environments tested:**    

OS: Ubuntu 23.04

Java version:  17

- [x] Most recent Paper version (1.20.1, git-Paper-17)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**  

### Before configuring balance requirement (set to 0)
![image](https://github.com/EssentialsX/Essentials/assets/12969145/0dfae8b7-5a82-42de-8817-a3347af9d254)
![image](https://github.com/EssentialsX/Essentials/assets/12969145/89e04e76-c091-4efe-b630-6ece50daf982)

### After configuring balance requirement
![image](https://github.com/EssentialsX/Essentials/assets/12969145/555a004f-b724-431f-bfdc-e2707c3f3da7)
![image](https://github.com/EssentialsX/Essentials/assets/12969145/e2406f7b-ad50-418c-91fd-96d088154fe9)

As you can see the name disappears from the list because min-balance required was 500 but the player had 499.

2023-06-17 00:01 UTC, JRoy requested changes
You need to maintain backwards compatibility for the `show-zero-baltop` config option.

2023-06-17 02:00 UTC, ayush03dev commented
> You need to maintain backwards compatibility for the `show-zero-baltop` config option.

I have re-added the above config option and made necessary checks along with the new options.

2023-06-17 23:11 UTC, JRoy requested changes

2023-06-17 23:11 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +    }
use config.getBigDecimal and return a BigDecimal

2023-06-18 01:33 UTC, ayush03dev commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +    }
For only double right, the `getBaltopMinBalance` method?

2023-06-18 18:21 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/Settings.java
> +    }
yeah :p

2023-06-20 12:40 UTC, YanisBft approved these changes

2024-11-25 03:00 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandbalancetop.java
>                              newCache.getLines().add(tl("balanceTopLine", pos, entry.getValue().getDisplayName(), NumberUtil.displayCurrency(entry.getValue().getBalance(), ess)));
```suggestion
                        if ((ess.getSettings().showZeroBaltop() || balance.compareTo(BigDecimal.ZERO) > 0)
                                && balance.compareTo(ess.getSettings().getBaltopMinBalance()) >= 0 &&
                                playTimeSecs > ess.getSettings().getBaltopMinPlaytime()) {
                            newCache.getLines().add(tl("balanceTopLine", pos, entry.getValue().getDisplayName(), NumberUtil.displayCurrency(balance, ess)));
```

2024-11-25 03:03 UTC, JRoy approved these changes
Thanks for the contribution :)

2024-11-25 03:06 UTC, merged