feat: discord name synchronisation
EssentialsX/Essentials pull request #5395
Opened 2023-06-16 11:57 UTC by gbaranski

### Information

This PR closes #5391. 

### Details

**Proposed feature:**  

Automatic synchronisation of Discord and Minecraft names.
Can work in two directions:
- MC -> Discord
- Discord -> MC

**Environments tested:**    

OS: Linux

Java version: 18

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

2023-06-16 12:05 UTC, gbaranski commented
As for now it doesn't really work, I'm not sure how to set nicknames 

https://github.com/gbaranski/Essentials/blob/dfdc0cf112c66a846e9a30b73325fe438f917cfb/EssentialsDiscordLink/src/main/java/net/essentialsx/discordlink/listeners/LinkBukkitListener.java#L41

```java
ess.getServer().dispatchCommand(Bukkit.getConsoleSender(), String.format("nickname %s %s", user.getName(), member.getEffectiveName()));
```

Does anyone have any idea how else it could be solved? Maybe somehow internally by sending NickChangeEvent?

2023-06-16 13:24 UTC, Octol1ttle requested changes

2023-06-16 13:24 UTC, Octol1ttle commented on EssentialsDiscordLink/src/main/java/net/essentialsx/discordlink/listeners/LinkBukkitListener.java
> +                ess.getServer().dispatchCommand(Bukkit.getConsoleSender(), String.format("nickname %s %s", user.getName(), member.getEffectiveName()));
Use the same code used in `/nick`: https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/commands/Commandnick.java#L110-L117

2023-06-16 13:24 UTC, Octol1ttle commented on EssentialsDiscordLink/src/main/java/net/essentialsx/discordlink/listeners/LinkBukkitListener.java
>              return;
The nickname synchronization code will not run due to this `return` if the link policy isn't set to kick unlinked players

2023-06-16 13:24 UTC, Octol1ttle commented on EssentialsDiscordLink/src/main/resources/config.yml
> +# In what mode names should be synchronised. Available modess:
```suggestion
# In what mode names should be synchronised. Available modes:
```

2023-06-16 13:24 UTC, Octol1ttle commented on EssentialsDiscordLink/src/main/java/net/essentialsx/discordlink/DiscordLinkSettings.java
> +    public NameSyncDirection getNameSyncDirection() { return nameSyncDirection; }
```suggestion
    public NameSyncDirection getNameSyncDirection() {
        return nameSyncDirection;
    }
```

2023-06-29 23:38 UTC, untuned commented on EssentialsDiscordLink/src/main/resources/config.yml
> +name-sync: none
I would probably mention the fact that the server owner will not be able to be synchronized, as bots cannot modify their nickname.

2024-01-08 11:27 UTC, closed without merging