Add PreKitExpandItemsEvent
EssentialsX/Essentials pull request #5407
Opened 2023-06-20 23:17 UTC by JRoy

Closes #5234

2023-06-21 22:50 UTC, YanisBft commented on Essentials/src/main/java/net/essentialsx/api/v2/events/PreKitExpandItemsEvent.java
> + * This event is not cancelable and is called right before items are about to be recieved by the {@link #getUser() user}.
```suggestion
 * This event is not cancellable and is called right before items are about to be received by the {@link #getUser() user}.
```

2023-06-21 23:13 UTC, YanisBft approved these changes

2023-07-01 21:09 UTC, mdcfe requested changes

2023-07-01 21:09 UTC, mdcfe commented on Essentials/src/main/java/net/essentialsx/api/v2/events/PreKitExpandItemsEvent.java
> +public class PreKitExpandItemsEvent extends Event {
```suggestion
public class KitPreExpandItemsEvent extends Event {
```

2023-07-01 21:09 UTC, mdcfe commented on Essentials/src/main/java/net/essentialsx/api/v2/events/PreKitExpandItemsEvent.java
> +    public PreKitExpandItemsEvent(IUser user, String kitName, List<ItemStack> itemStacks) {
```suggestion
    public KitPreExpandItemsEvent(IUser user, String kitName, List<ItemStack> itemStacks) {
```

2023-07-01 21:09 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/Kit.java
> +import net.essentialsx.api.v2.events.PreKitExpandItemsEvent;
```suggestion
import net.essentialsx.api.v2.events.KitPreExpandItemsEvent;
```

2023-07-01 21:09 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/Kit.java
> +            final PreKitExpandItemsEvent itemsEvent = new PreKitExpandItemsEvent(user, kitName, itemList);
```suggestion
            final KitPreExpandItemsEvent itemsEvent = new KitPreExpandItemsEvent(user, kitName, itemList);
```

2023-07-01 21:51 UTC, mdcfe approved these changes

2023-07-01 21:51 UTC, merged