Whitelist indicator in /seen and in /whois
EssentialsX/Essentials pull request #5486
Opened 2023-08-21 14:45 UTC by tazaxer

### Information

This PR closes #5481. 

### Details

**Proposed feature:**  

I've added a whitelist indicator on the commands whois and seen

When executing /whois the whitelist statusoof the target player will be displayed at the end as TRUE or FALSEm as TRUE or FALSE

When executing /seen and if the target player is offline the whitelist status of the target player will be displayed at the end as TRUE or FALSE

**Environments tested:**    

OS: MacOS 13.4.1

Java version:  17.0.5

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [x] CraftBukkit/Spigot/Paper 1.12.2
- [x] CraftBukkit 1.8.8

**Demonstration:**  

Before: https://imgur.com/a/mSFLzye
After: https://imgur.com/a/jiMvcmN

2023-08-22 14:45 UTC, JRoy requested changes
few things, overall good

2023-08-22 14:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/User.java
> +    public boolean isWhitelisted() {
We don't need a new method here, just use user.getBase().isWhitelisted() in /seen and /whois

2023-08-22 14:45 UTC, JRoy commented on Essentials/src/main/resources/messages_en.properties
> +whoisWhitelist=§6 - Whitelist\:§r {0}
This needs to go in messages.properties, not messages_en.properties

2023-08-22 14:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandwhois.java
> +        sender.sendMessage(tl("whoisWhitelist", user.isWhitelisted() ? tl("true") : tl("false")));
i'd prefer this is moved below the `whoisSpeed` line

2023-08-22 14:45 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandseen.java
> +        }
move this above line 154

2023-08-23 19:13 UTC, JRoy commented on Essentials/src/main/resources/messages.properties
> +whoisWhitelist=§6 - Whitelist\:§r {0}
```suggestion
whoisWhitelist=\u00a76 - Whitelist\:\u00a7r {0}
```

2023-08-23 19:13 UTC, JRoy approved these changes

2023-08-23 19:13 UTC, JRoy commented
Thanks

2023-08-23 19:20 UTC, merged

2023-08-24 07:00 UTC, takatalvi commented
Thank you so much for this!

2023-10-17 18:30 UTC, Bobcat00 commented
You guys are amazing:
https://github.com/EssentialsX/Essentials/pull/4618#issuecomment-974799094