Adds full support for socialspy in EssentialsDiscord
EssentialsX/Essentials pull request #5620
Opened 2024-01-23 08:24 UTC by mrbubbles06

### Information

This PR closes #5586. 

### Details

**Proposed feature:**  

Adds support for socialspy (viewing private messages) in EssentialsDiscord.

**Environments tested:**    

OS: MacOS 14.1

Java version: Temurin-17.0.10+7

- [x] Most recent Paper version (1.XX.Y, git-Paper-BUILD)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**  

<img width="557" alt="image" src="https://github.com/EssentialsX/Essentials/assets/37132465/13b119c2-ea03-4d1b-a110-e8aa8ed37356">
<img width="877" alt="image" src="https://github.com/EssentialsX/Essentials/assets/37132465/b803cb7e-3ee2-478c-b695-80a547f8d314">

2024-02-20 12:32 UTC, nelind3 commented
Looks great (I already ended up making a custom extension to do this because it was so needed for our moderation ability. It would be amazing to have it as a built in). Personally though I'd prefer it if the naming and formatting was more consistent with the rest of EssentialsX and EssentialsXDiscord namely:
- I think the message formatting should mirror the socialspy formatting. That is instead of `{sender-username} -> {receiver-username}: {message}` i think `[SS][{sender-displayname} -> {receiver-displayname}]: {message}` or similar is more appropriate.
- I think the message type name in the config should be something like `socialspy` or `private-message` in the same style as the other message types.

2024-02-20 16:07 UTC, Bobcat00 commented
> I think the message formatting should mirror the socialspy formatting. That is instead of `{sender-username} -> {receiver-username}: {message}` i think `[SS][{sender-displayname} -> {receiver-displayname}]: {message}` or similar is more appropriate.

I have a [PR](https://github.com/EssentialsX/Essentials/pull/5613) to make the Social Spy messages configurable to use either the player name or the display name (because player names are so much better for SS messages).

2024-02-21 20:03 UTC, nelind3 commented
If that does go through (which it really should display names versus player names are very much a thing that should be configurable) i think the socialspy formatting here should still mirror the in game socialspy formatting and it's defaults. If the default changes to socialspy using player names then this should default to player names too in my opinion. It's essentially the same message they should have the same default formatting.

2024-02-21 21:26 UTC, Bobcat00 commented
I agree. Also, my PR does not change the default being display names.

2025-03-24 17:03 UTC, JRoy requested changes

2025-03-24 17:03 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/listeners/BukkitListener.java
> +import org.bukkit.Bukkit;
```suggestion
```

2025-03-24 17:03 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/listeners/BukkitListener.java
> +                sender);
```suggestion

        if (event.getSender() instanceOf IUser && ((IUser) event.getSender()).isAuthorized("essentials.chat.spy.exempt")) {
            return;
        }

        sendDiscordMessage(MessageType.DefaultTypes.PRIVATE_CHAT,
                MessageUtil.formatMessage(jda.getSettings().getPmToDiscordFormat(),
                        MessageUtil.sanitizeDiscordMarkdown(event.getSender().getName()),
                        MessageUtil.sanitizeDiscordMarkdown(event.getSender().getDisplayName()),
                        MessageUtil.sanitizeDiscordMarkdown(event.getRecipient().getName()),
                        MessageUtil.sanitizeDiscordMarkdown(event.getRecipient().getDisplayName()),
                        MessageUtil.sanitizeDiscordMarkdown(event.getMessage())),
                sender);
```

2025-03-24 17:03 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/JDADiscordService.java
> +
```suggestion
```

2025-03-24 17:03 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/JDADiscordService.java
> +
```suggestion
```

2025-03-24 17:03 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/JDADiscordService.java
> +
```suggestion

```

2025-03-24 17:03 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/JDADiscordService.java
> +
```suggestion

```

2025-03-24 17:03 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/JDADiscordService.java
> +
```suggestion

```

2025-03-24 17:03 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/JDADiscordService.java
> +
```suggestion

```

2025-03-24 17:03 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/JDADiscordService.java
> +
```suggestion

```

2025-03-24 17:15 UTC, JRoy requested changes

2025-03-24 17:15 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/DiscordSettings.java
> +        pmToDiscordFormat = generateMessageFormat(getFormatString("private-chat"), "{sender-username} -> {receiver-username}: {message}", false,
```suggestion
        pmToDiscordFormat = generateMessageFormat(getFormatString("private-chat"), "[SocialSpy] {sender-username} -> {receiver-username}: {message}", false,
```

2025-03-24 17:15 UTC, JRoy commented on EssentialsDiscord/src/main/resources/config.yml
> +  pms-to-discord: "{sender-username} -> {receiver-username}: {message}"
```suggestion
  pms-to-discord: "[SocialSpy] {sender-username} -> {receiver-username}: {message}"
```

2025-03-24 17:39 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/listeners/BukkitListener.java
> +                sender);
```suggestion
                        MessageUtil.sanitizeDiscordMarkdown(event.getMessage())),
                        sender);
```

2025-03-24 17:43 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/listeners/BukkitListener.java
> +        if (event.getSender() instanceOf IUser && ((IUser) event.getSender()).isAuthorized("essentials.chat.spy.exempt")) {
```suggestion
        if (event.getSender() instanceof IUser && ((IUser) event.getSender()).isAuthorized("essentials.chat.spy.exempt")) {
```

2025-03-24 17:47 UTC, JRoy commented on EssentialsDiscord/src/main/java/net/essentialsx/discord/listeners/BukkitListener.java
> +                        sender);
```suggestion
                        event.getSender() instanceof IUser ? ((IUser) event.getSender()).getBase() : null);
```

2025-03-24 17:53 UTC, JRoy approved these changes

2025-03-24 17:53 UTC, JRoy commented
Sorry for the delay in approval and thanks for the contribution :)

2025-03-24 17:54 UTC, merged