Update to Minecraft 1.20.6
EssentialsX/Essentials pull request #5783
Opened 2024-04-30 02:21 UTC by JRoy

this compiles and probably works but there is some things still left to do

- [ ] test banner itemdb
- [ ] fix potion itemdb (see todos)
- [ ] update item aliases

2024-05-10 06:02 UTC, CyberFlameGO approved these changes
Changes look good to me - any ETA on a merge?

2024-05-13 13:08 UTC, Luftwaffle46 approved these changes
Awesome

2024-05-13 21:33 UTC, ImDarkLaw reviewed
Overall, changes look good. I noticed, however, that the following exception is still being printed in console when using `/give`. Perhaps that'd be something to address (or wait for Paper to resolve) before merging?

```log
[00:27:06 ERROR]: [org.bukkit.craftbukkit.util.CraftMagicNumbers] null
com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'minecraft:' at position 0: <--[HERE]

2024-05-15 12:44 UTC, Luftwaffle46 commented
> ```[00:27:06 ERROR]: [org.bukkit.craftbukkit.util.CraftMagicNumbers] null
> com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'minecraft:' at position 0: <--[HERE]
> ```

Correct me if im wrong, but im pretty sure that the 'minecraft:' prefix for an item is only supported in the vanilla '/give' command. For example, '/give @s minecraft:torch 1' would work in vanilla, but with essentials it would be '/give torch 1'.

2024-05-15 14:19 UTC, JRoy commented
> > ```[00:27:06 ERROR]: [org.bukkit.craftbukkit.util.CraftMagicNumbers] null
> > com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'minecraft:' at position 0: <--[HERE]
> > ```
> 
> Correct me if im wrong, but im pretty sure that the `minecraft:` prefix for an item is only supported in the vanilla `/give` command. For example, `/give @s minecraft:torch 1` would work in vanilla, but with essentials it would be `/give torch 1`.

the exception is unrelated to this and it is a (harmless) bukkit bug, nothing essentials can quite control.

2024-05-19 11:46 UTC, LOOHP commented
> > > ```
> > > com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown item 'minecraft:' at position 0: <--[HERE]
> > > ```
> > 
> > 
> > Correct me if im wrong, but im pretty sure that the `minecraft:` prefix for an item is only supported in the vanilla `/give` command. For example, `/give @s minecraft:torch 1` would work in vanilla, but with essentials it would be `/give torch 1`.
> 
> the exception is unrelated to this and it is a (harmless) bukkit bug, nothing essentials can quite control.

I've encountered this with my plugin when I used `Bukkit.getUnsafe().modifyItemStack`. Apparently, we have to include the item type in the `arguments` to avoid this error in 1.20.6.

For example, this prints the `CommandSyntaxException` error:
```java
Bukkit.getUnsafe().modifyItemStack(head, "minecraft:player_head[minecraft:profile={properties:[{name:\"textures\",value:\"" + base64 + "\"}]}]");
```

This does not:
```java
Bukkit.getUnsafe().modifyItemStack(head, "minecraft:player_head[minecraft:profile={properties:[{name:\"textures\",value:\"" + base64 + "\"}]}]");
```

Most likely this is already known by Essentials devs but I thought I'd leave it here if anyone else is looking up this problem.

2024-05-23 00:25 UTC, Budderman18 commented
im noticing some potions in kits do not work (all types instant damage pots, there might be more). They show up as "null" when trying to create it

2024-05-23 14:39 UTC, ImDarkLaw commented
> im noticing some potions in kits do not work (all types instant damage pots, there might be more). They show up as "null" when trying to create it

The issue with potions in kits, including instant damage potions (potion of harming), has been addressed in the latest commits to the [mc/1.20.5 branch](https://github.com/EssentialsX/Essentials/commits/mc/1.20.5/). Ensure you have pulled the latest changes from this branch and rebuilt the plugin. This should resolve potions showing up as *null*.

2024-05-23 17:59 UTC, Budderman18 commented
> > im noticing some potions in kits do not work (all types instant damage pots, there might be more). They show up as "null" when trying to create it
> 
> The issue with potions in kits, including instant damage potions (potion of harming), has been addressed in the latest commits to the [mc/1.20.5 branch](https://github.com/EssentialsX/Essentials/commits/mc/1.20.5/). Ensure you have pulled the latest changes from this branch and rebuilt the plugin. This should resolve potions showing up as _null_.

i am on the latest version of that branch and it still occurs.

Server version: 1.20.6-R0.1-SNAPSHOT 1.20.6-89-d3ffa62 (MC: 1.20.6)
Brand version: Paper
EssentialsX version: 2.21.0-dev+91-6bbc4a6

2024-05-23 18:23 UTC, JRoy commented
> > > im noticing some potions in kits do not work (all types instant damage pots, there might be more). They show up as "null" when trying to create it
> > 
> > The issue with potions in kits, including instant damage potions (potion of harming), has been addressed in the latest commits to the [mc/1.20.5 branch](https://github.com/EssentialsX/Essentials/commits/mc/1.20.5/). Ensure you have pulled the latest changes from this branch and rebuilt the plugin. This should resolve potions showing up as _null_.
> 
> i am on the latest version of that branch and it still occurs.
> 
> Server version: 1.20.6-R0.1-SNAPSHOT 1.20.6-89-d3ffa62 (MC: 1.20.6)
> Brand version: Paper
> EssentialsX version: 2.21.0-dev+91-6bbc4a6

when the server is stopped, delete the items.json file in the plugins/Essentials folder. When you start it, the issue should be resolved.

This will happen automatically once merged

2024-05-27 17:50 UTC, mdcfe requested changes

2024-05-27 17:50 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/Enchantments.java
> +        ENCHANTMENTS.put("depthstrider", Enchantment.DEPTH_STRIDER);
Breaking 1.7 support in 2024 smh

2024-05-27 17:50 UTC, mdcfe commented on Essentials/src/main/java/com/earth2me/essentials/MetaItemStack.java
> +            final int page = NumberUtil.isInt(split[0].substring(4)) ? Integer.parseInt(split[0].substring(4)) - 1 : 0;
IMO I prefer the extra brackets for clarity, even if they're technically redundant

2024-05-27 17:50 UTC, mdcfe commented on Essentials/src/main/resources/messages.properties
> +noMetaNbtKill=JSON NBT metadata is no longer supported, you must manually convert your defined items to data components. You can use Paper's tool to convert here: https://docs.papermc.io/misc/tools/i
```suggestion
noMetaNbtKill=JSON NBT metadata is no longer supported. You must manually convert your defined items to data components. You can convert JSON NBT to data components here: https://docs.papermc.io/misc/tools/item-command-converter
```
Slightly more explicit

2024-05-27 17:50 UTC, mdcfe commented on providers/BaseProviders/src/main/java/net/ess3/provider/providers/BaseBannerDataProvider.java
> +    public DyeColor getBaseColor(ItemStack stack) {
Is there really no better way to do this than a massive switch case

2024-05-27 19:51 UTC, mdcfe approved these changes

2024-05-27 19:53 UTC, merged