Implement kits placing items in specific slots
EssentialsX/Essentials pull request #5794
Opened 2024-05-07 08:28 UTC by TiagoFar78

Closes #5535

2025-10-05 04:30 UTC, JRoy requested changes
hi, sorry for the delay in review. overall, i think this pr is the wrong approach. we should be adding a `slot:<number>` into `MetaItemStack` where `expandItems` will attempt to add the item to that slot if it is not full.

2025-11-18 01:21 UTC, TiagoFar78 commented
> we should be adding a `slot:<number>` into `MetaItemStack`

I like the idea of storing the item slot like that, but it should not live in `MetaItemStack`. The slot is an inventory attribute, not an item attribute. If you put it in the item metadata, any serialization provider that saves only the item would lose the slot information and be unable to restore it later.

```java
if (kitItem.startsWith("@")) {
	if (serializationProvider == null) {
		ess.getLogger().log(Level.WARNING, AdventureUtil.miniToLegacy(tlLiteral("kitError3", kitName, user.getName())));
		continue;
	}
	stack = serializationProvider.deserializeItem(Base64Coder.decodeLines(kitItem.substring(1)));
} else {
	final String[] parts = kitItem.split(" +");
	final ItemStack parseStack = ess.getItemDb().get(parts[0], parts.length > 1 ? Integer.parseInt(parts[1]) : 1);

	if (parseStack.getType() == Material.AIR) {
		continue;
	}

	final MetaItemStack metaStack = new MetaItemStack(parseStack);

	if (parts.length > 2) {
		// We pass a null sender here because kits should not do perm checks
		metaStack.parseStringMeta(null, allowUnsafe, parts, 2, ess);
	}

	stack = metaStack.getItemStack();
}

itemList.add(stack);
```

---

> where `expandItems` will attempt to add the item to that slot if it is not full.

Should `expandItems` try to place every item from a kit into its assigned slot rather than only armor and offhand, and if it does, should the command include a flag to disable this behavior? Editing the config to remove slot data is technically possible.

2025-12-07 22:06 UTC, JRoy commented
hmm you're right, it should stay in expandItems.

Instead of an slotList tho, lets do a HashMap<Integer, ItemStack>, if during put() we get a return value (overlapping slot), add it to the regular itemList .

then we should do the Inventories#hasSpace check with all items (both regular and slotted) (or isDropItemsIfFull)

then we'll have a new method in Inventories that will check isSimilar and if the amount + new amount will be greater than the allowed max size. that method will return a boolean if it can be added to the slot or not.

then finally add all the non-slotted items + ones that couldn't be added to the slot they asked for in one go via Inventories#addItem

2026-02-07 05:48 UTC, JRoy approved these changes

2026-02-07 05:49 UTC, JRoy commented
thank you!

2026-02-07 05:53 UTC, merged