Add argument to /skull to give skull to other player
EssentialsX/Essentials pull request #5822
Opened 2024-06-05 19:00 UTC by Yurakaii

### Information

This PR closes #5762. 

### Details
**Proposed feature:**  
This adds the ability to give a skull to another player using the /skull command with a second argument, if you only provide one argument the command will work as it previously did.

The new usage of the skull command is:
`/<command> [owner] [player]`

**Environments tested:**    

OS: Windows 11

Java version:  21

- [x] Most recent Paper version (1.20.6, git-Paper-137)
- [ ] CraftBukkit/Spigot/Paper 1.12.2
- [ ] CraftBukkit 1.8.8

**Demonstration:**  

This gives the dinnerbone's skull to trashdrumlinfly:
![Screenshot 2024-06-05 144150](https://github.com/EssentialsX/Essentials/assets/78126278/4ab40113-5c10-4fe5-9da5-dd680480cff3)

trashdrumlinfly received dinnerbone's skull
![Screenshot 2024-06-05 143929](https://github.com/EssentialsX/Essentials/assets/78126278/ce93b9d2-eb5a-4e94-9742-cc20df709010)

The command can still be used as how it worked before by just providing the first argument.

2024-07-23 19:54 UTC, JRoy requested changes
overall looks fine, can you just update the `skullCommandUsage` messages in the `messages.properties` file

2024-08-26 08:36 UTC, CatTeaA commented
bump

2024-10-16 09:00 UTC, Huge-mistake commented
> overall looks fine, can you just update the `skullCommandUsage` messages in the `messages.properties` file

Apologies for the interruption, can this PR be merged now? I would like to utilize this feature in the menu to provide players with skulls.

2024-11-25 01:37 UTC, JRoy commented on Essentials/src/main/java/com/earth2me/essentials/commands/Commandskull.java
> +        if(args.length == 2){
```suggestion
        if (args.length == 2) {
```

2024-11-25 01:41 UTC, JRoy approved these changes

2024-11-25 01:42 UTC, merged

2024-11-25 01:42 UTC, JRoy commented
Thanks for the contribution :)