Fix respawn-at-anchor setting.
EssentialsX/Essentials pull request #5825
Opened 2024-06-07 23:35 UTC by gibsonpil

Closes #5824.

2024-06-09 15:21 UTC, gibsonpil commented on EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/EssentialsSpawnPlayerListener.java
I'm curious to know what the standard manner of handling recently deprecated functions without functional equivalents in older version is within EssentialsX. This is the best I could come up with, but if there is a preferred way of doing this I'd be happy to switch over to it.

2024-06-30 00:41 UTC, zp4rker commented on EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/EssentialsSpawnPlayerListener.java
I believe the best way to do this is by using providers. https://github.com/EssentialsX/Essentials/tree/2.x/providers

You can create a base provider interface, then implement a legacy and modern one.

2024-07-23 20:03 UTC, JRoy requested changes

2024-07-23 20:03 UTC, JRoy commented on EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/EssentialsSpawnPlayerListener.java
> +                }
Please use `VersionUtil` checks here, that stack trace can be expensive especially if this is hot code

2024-07-23 20:03 UTC, JRoy requested changes
just one thing otherwise fine

2024-07-23 23:10 UTC, gibsonpil commented
Alright, I switched it over to using `VersionUtil` and rebased everything. :smile:

2024-07-23 23:14 UTC, gibsonpil commented on EssentialsSpawn/src/main/java/com/earth2me/essentials/spawn/EssentialsSpawnPlayerListener.java
I looked over the other providers that were implemented and it appears that the bulk of them are for translating multiple class fields across different iterations of the Bukkit API. I'm not sure that it'd be worth it to implement such a thing for a one-off method call, and it'd certainly add unnecessary design complexity.

2024-11-25 03:13 UTC, JRoy approved these changes

2024-11-25 03:14 UTC, JRoy commented
Thanks for the contribution :)

2024-11-25 03:15 UTC, merged