Create `/itemname` command that names held items.
EssentialsX/Essentials pull request #672
Opened 2016-06-21 23:41 UTC by SupaHam

This PR creates a class named `Commanditemname` alongside the addition in `plugin.yml`.

**Aliases**: [iname, einame, eitemname]

The command allows players to name their held items. It follows the conventions of `FormatUtil#formatString(IUser, String, String)`. Where the permBase string (1st arg) is `essentials.itemname`. This means in order to use colouring in itemname one must have the `essentials.itemname.color` permission.

This PR also adds two new translatable messages `itemnameInvalidItem` and `itemnameSuccess`.

2016-06-22 07:15 UTC, Bammerbom commented on Essentials/src/messages.properties
> +itemnameInvalidItem=\u00a7cThat item material cannot be name.
incorrect english

2016-07-10 00:01 UTC, vemacs commented
For most servers (those that rely on crate keys, etc), there should be a permissions check to deny/allow specific materials for renaming.

2016-07-13 21:33 UTC, Phoenix616 commented
The permissions should probably be ```essentials.itemname.item-<itemname>```/```essentials.itemname.item-<itemid>```/```essentials.itemname.item-all``` to follow the same schema as the other per item type permission. (e.g. the give one)

2017-11-06 15:50 UTC, Sikatsu commented
@SupaHam Is there any reason why this isn't added yet? Would like to see it implemented.

2018-07-05 18:25 UTC, TheIntelloBox commented
Could you implement it please ? :D

2019-01-09 22:04 UTC, mdcfe requested changes
I know this is reviving an old PR that hasn't been touched for a while, but there were a few things I noticed could be improved.

2019-01-09 22:04 UTC, mdcfe commented on Essentials/src/messages.properties
> +itemnameInvalidItem=\u00a7cThat item material cannot be renamed.
This message is only sent when the player isn't holding anything - `itemnameAir=\u00a7cYou need to hold an item to rename it.` might be a better message, unless there are actual materials that can't be renamed for some reason.

2019-01-09 22:04 UTC, md678685 commented on Essentials/src/plugin.yml
> +    aliases: [iname, einame, eitemname]
We could add `/rename` and `/erename`.

2019-05-30 14:22 UTC, md678685 commented
Closing in favour of #2573.

2019-05-30 14:22 UTC, closed without merging